- docs/architecture/README.md
- docs/architecture/adr-001-repo.md
- docs/architecture/adr-template.md
ADR summarizing recent discussion and issues like https://github.com/interchainio/tendermint-rs/issues/7
> docs/arch: add readme and adr-001

- tendermint/src/lib.rs
- tendermint/tests/config.rs
- tendermint/tests/rpc.rs
I couldn't figure out how to remove the `extern crate` with the rename here. I read https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html#renaming-crates, but couldn't get it working. Possibly it's because I needed to edit *alot* more files, but didn't feel I should have to do that. So I also tried https://doc.rust-lang.org/1.28.0/cargo/reference/unstable.html#rename-dependency, but couldn't get it working either. So I just turned off the lint in one spot ...
Also the `config_toml_parser` could be broken out a bit but didn't seem like a big deal to just disable the lint for now.
> Address clippy warnings

- tendermint/src/amino_types/message.rs
- tendermint/src/vote.rs
So we have identical signing bytes as golang version to verify signatures.
> Signing bytes need to encoded with encode_length_delimited

- tendermint/src/merkle.rs
- tendermint/src/validator.rs
> simple_hash_from_byte_slices takes a Vec instead of slice

- tendermint/src/abci/code.rs
- tendermint/src/abci/data.rs
- tendermint/src/abci/log.rs
- tendermint/src/abci/transaction.rs
- tendermint/src/block/commit.rs
- tendermint/src/block/id.rs
- tendermint/src/channel.rs
- tendermint/src/evidence.rs
- tendermint/src/hash.rs
- tendermint/src/node/info.rs
- tendermint/src/rpc/endpoint/abci_query.rs
- tendermint/src/rpc/endpoint/broadcast/tx_commit.rs
- tendermint/src/time.rs
- tendermint/src/vote/power.rs
I removed the ``Default`` instances that don't make sense.
> Implement utility traits for tendermint data types

- tendermint/src/amino_types/block_id.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/block/header.rs
- tendermint/src/block/id.rs
- tendermint/src/genesis.rs
- tendermint/src/hash.rs
- tendermint/src/rpc/endpoint/abci_info.rs
- tendermint/src/rpc/endpoint/status.rs
- tendermint/src/serializers.rs
- tendermint/src/validator.rs
Fix panic when dealing with empty block id in the first block.
> Handle empty block id

- tendermint/src/amino_types/block_id.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/block/header.rs
- tendermint/src/block/id.rs
- tendermint/src/genesis.rs
- tendermint/src/hash.rs
- tendermint/src/lite/types.rs
- tendermint/src/rpc/endpoint/abci_info.rs
- tendermint/src/rpc/endpoint/status.rs
- tendermint/src/serializers.rs
- tendermint/src/validator.rs
- tendermint/tests/lite.rs
- tendermint/tests/support/lite/basic.json
Add some mocking data to test lite client.
> add mock testing for lite client

- tendermint/src/validator.rs
* `Debug` of `Error` is for printing error.
* `Serialize/Deserialize` of `validator::Set` is because it's a part of the trusted state, which needs to be stored somewhere.
> Implement several utility trait

- tendermint/src/genesis.rs
- tendermint/src/validator.rs
- tendermint/tests/support/rpc/genesis.json
`genesis` endpoint response has a `validators` field, which is similar to the one from `validators` endpoint, we can re-use the data type for this, only difference is the field name of `voting_power` becomes `power`.
> Parse validators field in genesis api

- tendermint/Cargo.toml
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/block/height.rs
- tendermint/src/rpc/endpoint/abci_query.rs
- tendermint/src/serializers.rs
- tendermint/tests/integration.rs
This is a fix for #75, although it's not passing the integration test yet since Tendermint is responding with "0" for the `height` field but `block::Height` enforces that height is >= 1. Other unrelated integration tests are also failing, other RPC request/response types are possibly out of date or just overly strict.
> Fix abci_query RPC endpoint

- tendermint/Cargo.toml
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/block/header.rs
- tendermint/src/block/height.rs
- tendermint/src/serializers.rs
- tendermint/src/validator.rs
- tendermint/tests/integration.rs
list d25519-dalek dep, adapt to renaming (simple_merkle hickup), and fmt:
- #77 introduced an fmt issue
- #36 was not up-to date regarding changes which were merged to master (renaming
of simple_merkle)
- new upstream release of made build of master fail (solution: explicitly add it
ed25519-dalek (1.0.0-pre.3) with rand feature fixes that
> Fix build on master

- tendermint/src/abci/transaction.rs
- tendermint/src/block/size.rs
I'm not sure about the specification of ``max_gas``, but the default ``genesis.conf`` generated by ``tendermint`` has ``max_gas`` set to ``-1``, so.
> Change type of ``max_gas`` to i64, and remove two clones.

- tendermint/Cargo.toml
- tendermint/src/rpc/client.rs
- tendermint/src/rpc/error.rs
- tendermint/src/rpc/response.rs
- tendermint/tests/integration.rs
- tendermint/tests/rpc.rs
The crate itself builds with these changes, but the tests don't.
I'm not sure how to write tests for this (it's my first time using `async`/`await` in Rust 😅)
> Upgrade to hyper v0.13; use async/await

- tendermint/Cargo.toml
- tendermint/src/rpc/id.rs
`rand_os` is just a wrapper for `getrandom`. I believe the long-term plan is to deprecrate it entirely.
> Replace `rand_os` with `getrandom` (closes #23)

- tendermint/src/block/signed_header.rs
- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
- tendermint/src/validator.rs
As per #96, this removes the Validator trait by making ValidatorSet an associated type of Commit. As a bonus, we eliminate dependency on the `Id` type from the light module.
This allows implementations of Commit to access underlying functionality of a validator set (like its validators and signature verification with them) without requiring that functionality to be part of the light client module. This should also make it much easier to write tests for the module now, since we don't need to mock a `verify_signature`.
I'm not sure if this is the best way to do things, but it seems to be along the right lines ...
> remove Validator trait; make ValidatorSet associated to Commit

- tendermint/src/block/signed_header.rs
- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
- tendermint/src/validator.rs
Initial mock and test for the Header and `is_within_trust_period`.
I hesitated on mocking the Commit because it ultimately requires Validator, which has a `verify_signature` method, which I think we'd like to avoid needing to test this core logic (ie. https://github.com/interchainio/tendermint-rs/issues/96#issuecomment-569360555).
We should consider some more changes to the traits to eliminate the need for this. It will make mocking everything much easier!
> MockHeader and test_is_within_trust_period

- tendermint/src/block/commit.rs
- tendermint/src/consensus/state.rs
New clippy errors since the latest rust stable release:
<details><summary>Expand circle log</summary>
<p>
```
error: redundant clone
--> tendermint/src/block/commit.rs:35:15
|
35 |         self.0.clone()
|               ^^^^^^^^ help: remove this
|
note: lint level defined here
--> tendermint/src/lib.rs:8:5
|
8  |     warnings,
|     ^^^^^^^^
= note: `#[deny(clippy::redundant_clone)]` implied by `#[deny(warnings)]`
note: this value is dropped without further use
--> tendermint/src/block/commit.rs:35:9
|
35 |         self.0.clone()
|         ^^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
error: `if` chain can be rewritten with `match`
--> tendermint/src/consensus/state.rs:52:9
|
52 | /         if self.height < …
```
> Fix clippy errors

- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
- tendermint/tests/lite.rs
Some changes to #100 in separate PR to s.t. other PRs (#104, #105 etc) don't need to rebase / merge
> Review comments:

- tendermint/src/block/commit.rs
- tendermint/src/block/signed_header.rs
- tendermint/src/consensus/state.rs
- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
- tendermint/src/validator.rs
- tendermint/tests/lite.rs
Needs tests with concrete impls of store and requester. (e.g. simple in memory store in form of a map and a mocked rpc client).
ref: #96
> Light client: bisection, store, requester

- tendermint/src/lite/public.rs
- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
First take at some tests for the new `verify_single` function, ala #113 
This completes an implementation of mocks for the core types for the lite module and shows how to use them for testing. Still unmocked are the `Store` and `Requester`.
There's probably much to be improved here, including the test names and how we organize them, but this seems like a decent start.
This also surfaced some issues with error types:
- when used to verify a commit (rather than just checking if we can skip), `voting_power_in` can't detect signatures from validators not in the current validator set
- we should have two distinct errors for InsufficientVotingPower - one when it's insufficient to skip, and one when it's insufficient to verify! Otherwise we might start bisecting when really the commit is just …
> Lite: complete test mocks and start some tests

- tendermint-lite/src/lib.rs
- tendermint-lite/src/main.rs
- tendermint-lite/src/requester.rs
- tendermint-lite/src/state.rs
- tendermint-lite/src/store.rs
- tendermint-lite/src/threshold.rs
- tendermint/src/lite/public.rs
- tendermint/src/rpc/endpoint/commit.rs
First take at hooking it all up into a running light node!
It currently fails I think because we're computing header hashes incorrectly ...
> first take at hooking up a node

- CHANGES.md
- tendermint/Cargo.toml
- tendermint/src/amino_types/block_id.rs
- tendermint/src/amino_types/ed25519.rs
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/remote_error.rs
- tendermint/src/amino_types/time.rs
- tendermint/src/amino_types/version.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/lib.rs
- tendermint/src/rpc/client.rs
- tendermint/src/validator.rs
Update to bytes_0.5 and amino_rs 0.5 and makes all the amino_rs tokens independent of prost tokens enabling prost and amino_rs to be combined in a dependency.
> Update to bytes 0.5 and amino_rs 0.5

- tendermint/src/amino_types/block_id.rs
- tendermint/src/amino_types/ed25519.rs
- tendermint/src/amino_types/message.rs
- tendermint/src/amino_types/ping.rs
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/remote_error.rs
- tendermint/src/amino_types/signature.rs
- tendermint/src/amino_types/time.rs
- tendermint/src/amino_types/version.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/error.rs
- tendermint/src/lib.rs
- tendermint/src/validator.rs
They were used as a hack around an old version of `prost`.
Now that `amino_rs` is properly namespaced, we don't need them.
> Remove `extern crate` directives

- tendermint/Cargo.toml
Main upstream change is an `ecdsa` crate upgrade. Changelog here:
https://github.com/RustCrypto/signatures/pull/69
> Update to `signatory` v0.18

- tendermint-lite/src/main.rs
- tendermint/Cargo.toml
- tendermint/src/amino_types.rs
- tendermint/src/amino_types/ed25519.rs
- tendermint/src/amino_types/ping.rs
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/vote.rs
I'd like to compute some Amino type prefixes in something other than the KMS (namely an oracle feeder) and unfortunately the code to do so is presently vendored into the KMS, and used to compute these prefixes (with a TODO to move it elsewhere):
https://github.com/tendermint/kms/blob/master/src/rpc.rs#L45
It seems like these should go with the Amino types. Perhaps the `compute_prefix` method should be moved into the `amino_rs` crate.
> Move Amino type prefixes over from KMS

- tendermint/src/lite/verifier.rs
Updates:
- refactored init_requester to take vector of commits (previously, it assumed all the Vals have signed)
- updated existing tests for the new init_requester
- added bisection test for insufficient commits
> Refactor init_requester

- tendermint-lite/src/main.rs
- tendermint-lite/src/requester.rs
- tendermint-lite/src/store.rs
- tendermint/src/lite/error.rs
- tendermint/src/lite/types.rs
- tendermint/src/lite_impl/signed_header.rs
- tendermint/src/rpc/error.rs
Followup to #149:
- remove `InvalidSignature` and `InvalidCommitSignatures`
- introduce `ImplementationSpecific` Kind instead
- simplify `RequestFailed` in the same way
closes #149
> Light errors: Remove `InvalidSignature` and `InvalidCommitSignatures` 

- tendermint/tests/lite.rs
> Fix build on master 🔧💚

- tendermint-lite/src/main.rs
- tendermint/src/lite/error.rs
- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
- tendermint/src/lite_impl/signed_header.rs
- tendermint/tests/lite.rs
> Followup on 149 and 151

- tendermint/Cargo.toml
- tendermint/src/abci/data.rs
- tendermint/src/abci/gas.rs
- tendermint/src/abci/log.rs
- tendermint/src/abci/transaction/hash.rs
- tendermint/src/account.rs
- tendermint/src/amino_types/block_id.rs
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/signature.rs
- tendermint/src/amino_types/validate.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/block/height.rs
- tendermint/src/chain/id.rs
- tendermint/src/config.rs
- tendermint/src/config/node_key.rs
- tendermint/src/config/priv_validator_key.rs
- tendermint/src/error.rs
- tendermint/src/hash.rs
- tendermint/src/lib.rs
- tendermint/src/lite/types.rs
- tendermint/src/net.rs
- tendermint/src/node/id.rs
- tendermint/src/public_key.rs
- tendermint/src/rpc/error.rs
- tendermint/src/time.rs
- tendermint/src/timeout.rs
- tendermint/tests/lite.rs
Consistent error handling across the repo. 
I have written up some notes briefly explaining what "consistent" means here. ~~Will post them~~ Posted in https://github.com/interchainio/tendermint-rs/issues/150#issuecomment-586148337. They can be used for an ADR if that's desired.
closes #150
> Refactor errors 

- tendermint/src/rpc/client.rs
One-liner that fixes the build again.
I've verified that this change doesn't modify the current logic/init. See https://github.com/hyperium/hyper/pull/2142/files for yourself in case you have doubts.
ref https://circleci.com/gh/interchainio/tendermint-rs/1202
closes #165
> rpc: remove usage of deprecated method in client

- tendermint-lite/src/main.rs
- tendermint-lite/src/requester.rs
- tendermint/src/rpc/client.rs
- tendermint/tests/integration.rs
See #168 for the rationale behind this change.
In addition, both methods now take ownership of the `rpc::Address` rather than cloning a reference. This avoids unnecessary clones when the caller already has ownership of the address.
> Turn `rpc::Client::new` into a sync fn by not performing the health check on creation

- tendermint-lite/Cargo.toml
- tendermint-lite/src/main.rs
- tendermint-lite/src/requester.rs
- tendermint/Cargo.toml
- tendermint/src/lite/types.rs
- tendermint/src/lite/verifier.rs
- tendermint/tests/lite.rs
Closes: #170
On top of the changes mentioned in the linked issue, `lite::verifier::verify_bisection_inner` had to be manually adapted to return a boxed future because recursive async fn are not currently supported in Rust.
An possible alternative would be to rewrite `verify_bisection_inner` to not be recursive anymore, but that is outside of the scope of this PR.
> Turn `lite::types::Requester` into an async trait

- tendermint/src/lite/verifier.rs
> Publicly export more functions from `lite::verifier`

- .github/workflows/rust.yml
- CHANGES.md
- tendermint/src/genesis.rs
- tendermint/src/rpc/endpoint/abci_info.rs
- tendermint/src/rpc/endpoint/abci_query.rs
- tendermint/tests/integration.rs
- tendermint/tests/rpc.rs
> Enable integration tests + GitHub Actions Service for Tendermint node

- tendermint/src/lite/verifier.rs
#171 introduced async tests in the verifier. It seems that also tests that don't call async functions were marked as async (which doesn't harm but makes the tests look as if they were calling async functions). This small PR reverts this.
ref https://github.com/informalsystems/tendermint-rs/pull/171#discussion_r399712319
> make tests sync instead of async where no async function is used

- tendermint/src/lite/types.rs
- tendermint/tests/support/serialization/trust_threshold/fraction.json
> Add missing serializer for TrustThresholdFraction fields

- tendermint/Cargo.toml
- tendermint/src/account.rs
I just manually created a test vector since I couldn't use the go tendermint vector (I didn't look into what the extra address bytes were there and assumed that's handled somewhere else here)
Want me to add this in CHANGES.md?
Edit: Everything passes on stable and nightly toolchain locally, and I can't see why CI failed for some reason
> Update secp address hash

- light-node/Cargo.toml
- tendermint/Cargo.toml
This release of `signatory` uses the v1.0 releases of the `ed25519` and `signature` crates. Release announcement for those here:
https://www.reddit.com/r/rust/comments/g4w8by/ann_rustcrypto_signature_v10_and_ed25519_v10/
It also eliminates the needless dependencies on the `p256` and `p384` crates, which `tendermint-rs` doesn't use (it only uses the `k256` crate for the secp256k1 curve definition).
> Update `signatory` requirement to v0.19

- tendermint/src/evidence.rs
- tendermint/src/rpc/endpoint/abci_info.rs
- tendermint/tests/rpc.rs
- tendermint/tests/support/rpc/block_with_evidences.json
Removed `new` and `to_amino_bytes` methods.
> Fix #241 evidence JSON format

- tendermint/tests/support/lite/single_step_sequential/commit_tests.json
- tendermint/tests/support/lite/single_step_skipping/commit_tests.json
I have only made quick fixes to the failing commit tests because `timestamp` serialization needs to be fixed on the Go side. For now, I've changed it to `null` so that it parses. 
Also, there is a confusion whether `validator_address` is optional or not for an absent CommitSig ([comment](https://github.com/informalsystems/tendermint-rs/pull/248#discussion_r419794099))
> Temporary JSON test fixes

- CHANGES.md
- tendermint/tests/integration.rs
Fixes issue #249 
PR #255 soft-depends on this PR for integration test success.
> Update abci_info test to 0.17.0

- tendermint/src/block.rs
- tendermint/src/block/commit.rs
- tendermint/src/block/header.rs
- tendermint/src/block/parts.rs
- tendermint/src/block/size.rs
- tendermint/src/channel.rs
- tendermint/src/consensus/state.rs
- tendermint/src/evidence.rs
- tendermint/src/lite/types.rs
- tendermint/src/node/info.rs
- tendermint/src/rpc/endpoint/abci_info.rs
- tendermint/src/rpc/endpoint/abci_query.rs
- tendermint/src/rpc/endpoint/net_info.rs
- tendermint/src/serializers.rs
- tendermint/src/vote.rs
- tendermint/tests/lite.rs
- tendermint/tests/serialization.rs
Context: https://github.com/informalsystems/tendermint-rs/pull/255#discussion_r422116612
> Refactoring: rename serializers

- CHANGES.md
- tendermint/src/abci/proof.rs
- tendermint/src/block.rs
- tendermint/src/block/commit.rs
- tendermint/src/block/header.rs
- tendermint/src/block/parts.rs
- tendermint/src/block/size.rs
- tendermint/src/channel.rs
- tendermint/src/consensus/state.rs
- tendermint/src/evidence.rs
- tendermint/src/lib.rs
- tendermint/src/lite/types.rs
- tendermint/src/node/info.rs
- tendermint/src/rpc/endpoint/abci_info.rs
- tendermint/src/rpc/endpoint/abci_query.rs
- tendermint/src/rpc/endpoint/net_info.rs
- tendermint/src/serializers.rs
- tendermint/src/vote.rs
- tendermint/tests/lite.rs
- tendermint/tests/serialization.rs
- Refactor the serializer library. Move all functions into modules and rewrite the annotation to use `with`. (Looks nicer.)
This is a first step in refactoring serialization outloined in issue #247  .
Soft-depends on Issue #249 / PR #256 for integration test success.
> Serialization refactor step 1

- CHANGES.md
Updates to CHANGES.md: added the changes implemented in the earlier Tendermint/v0.33 change.
> Updated CHANGES.md

- tendermint/src/serializers.rs
Try out if https://github.com/informalsystems/tendermint-rs/pull/269#discussion_r425005565 really works.
> Alternative to visitor and enum

- CHANGES.md
- tendermint/src/rpc/endpoint/abci_query.rs
- tendermint/src/serializers.rs
- tendermint/tests/integration.rs
- tendermint/tests/serialization.rs
Implemented null-value deserialization for Vec<u8> using Visitor.
This is part 2 of the serialization improvement efforts described in #247 .
(This PR was opened after part 1 was merged. It was easier to open this than to keep the original #257)
This PR is ready for review.
> Serialization refactor step 2

- tendermint/Cargo.toml
- tendermint/src/rpc/event_listener.rs
- tendermint/tests/integration.rs
> Simplify event subscription

- CHANGES.md
- tendermint/Cargo.toml
- tendermint/src/block/commit_sig.rs
- tendermint/src/lite_impl/signed_header.rs
- tendermint/src/serializers.rs
- tendermint/src/serializers/custom.rs
- tendermint/src/serializers/raw_commit_sig.rs
- tendermint/src/serializers/tests.rs
This is a second - slightly less complex - stab at refactoring CommitSig.
Resolves the following:
#247 - CommitSig refactor
#259 - CommitSig timestamp can be "0000" time instead of null (Go compatibility issue)
#260 - CommitSig validator address not present in Absent votes (Go compatibility issue)
- The two compatibility issues had to be included or else the tests would have failed. With that said, the compatibility issues should remain open until they are fixed in the Go code. The fixed code is also included here and it's commented out.
Please review and comment. We can change the way we deal with the compatibility code, if this looks unruly.
~~- @melekes had two questions in a previous review of this code: where is the validator_address validation (I think that was not implemented …
> CommitSig refactor

- CHANGES.md
- tendermint/src/block.rs
- tendermint/src/serializers/custom.rs
- tendermint/src/serializers/tests.rs
Fixes #261 
Reimplements #98 because of too many changes from master.
Note: #98 is @yihuang 's PR and I want to credit him with the findings. Cherry-picking his changes to master didn't work out, too many files changed since he opened the PR.
> Symmetric assertions to unit tests

- tendermint/src/lite_impl/signed_header.rs
- tendermint/tests/lite.rs
The block_id of nil vote should be `None`, otherwise, the signature verify fails.
> Fix block_id of nil vote

- docs/spec/lightclient/verification.md
This PR also:
- Renames `Pivot` to `Schedule` to match the light client ADR nomenclature.
- Reformats a few blocks here and there to improve legibility of the plaintext spec.
> Add missing tags for pre/postconditions to the Light Client english spec

- tendermint/src/block/commit_sig.rs
- tendermint/src/lite_impl/signed_header.rs
- tendermint/src/serializers/raw_commit_sig.rs
Addressing @melekes review comments as part of https://github.com/informalsystems/tendermint-rs/issues/211. 
Note that there is one [comment](https://github.com/informalsystems/tendermint-rs/pull/196#discussion_r409502161) still unaddressed but it is tracked separately already and the code might change due the ongoing light client refactoring.
> 0.33 compat followup

- tendermint/tests/lite.rs
Quickfix that closes #276 (I had this change uncommited in my workspace and just pushed it)
> light tests: remove assertions about number of bisections

- tendermint/src/rpc/id.rs
https://github.com/informalsystems/tendermint-rs/pull/196#discussion_r399790732
part of https://github.com/informalsystems/tendermint-rs/issues/211
> Add tests for jsonrpc id

- light-client/Cargo.toml
- light-client/examples/light_client.rs
- light-client/src/components.rs
- light-client/src/components/fork_detector.rs
- light-client/src/components/io.rs
- light-client/src/components/scheduler.rs
- light-client/src/components/verifier.rs
- light-client/src/contracts.rs
- light-client/src/errors.rs
- light-client/src/lib.rs
- light-client/src/light_client.rs
- light-client/src/macros.rs
- light-client/src/predicates.rs
- light-client/src/predicates/errors.rs
- light-client/src/prelude.rs
- light-client/src/state.rs
- light-client/src/store.rs
- light-client/src/store/sled.rs
- light-client/src/store/sled/utils.rs
- light-client/src/tests.rs
- light-client/src/types.rs
- light-client/tests/light_client.rs
- tendermint/src/lite/types.rs
> Light Client: Follow-up

- tendermint/src/rpc.rs
- tendermint/src/rpc/event_listener.rs
Non-elegant quickfix: makes all event subscription fields `pub` s.t. they can be accessed and processed. 
close #308
> Quickfix: make fields in event subscription accessible publicly

- tendermint/src/rpc/event_listener.rs
As per title, need to be able to clone this.
> add Clone to EventSubscription

- .github/workflows/rust.yml
- CHANGES.md
- tendermint/tests/integration.rs
Closes #304
With this change, CI runs two integration tests:
1. A `stable` test to protect against regressions, run against a pinned
version of the tendermint/tendermint docker image.
2. A `latest` test to track whether we're maintaining parity with the
latest development version of tendermint-go.
IIUC, we'd ideally like (1) to be a required test, and to get visibility on (2) but not block the PR if it fails. I can configure (2) so that it the job succeeds even if the step fails, but then we lose clear visibility on the failure.
Please see individual commits for more detail.
> Add integration test pinned to tendermint-go v0.33.5

- .github/workflows/rust.yml
- CHANGES.md
Closes #304
Followup to #324 
Signed-off-by: Shon Feder <shon@informal.systems>
> Set integration-test-latest to continue_on_error

- tendermint/Cargo.toml
- tendermint/src/amino_types.rs
Updates:
`ripemd160` v0.8 => v0.9
`sha2` v0.8 => v0.9
`signatory` v0.19 => v0.20
> Update signatory to v0.20

- light-node/Cargo.toml
- rpc/Cargo.toml
- rpc/src/client.rs
- rpc/src/client/event_listener.rs
- rpc/src/error.rs
- rpc/src/lib.rs
- tendermint/Cargo.toml
Guard client code paths To avoid the transient dependency on net related crates for users who are primarily interested in the core types.
Follow-up #339
Ref #337
> rpc: guard client with feature flag

- light-client/src/callback.rs
- light-client/src/operations/voting_power.rs
- light-client/src/predicates.rs
- light-client/src/predicates/errors.rs
- light-client/src/supervisor.rs
- light-client/src/types.rs
- light-client/tests/light_client.rs
- tendermint/src/block/commit_sig.rs
- tendermint/src/lite/types.rs
Fix #282 
Fix #335
- Provide two helper methods for checking validators overlap and if there is enough trust w.r.t. the trusted state
- Only count `Commit` signatures towards the voting power (#282)
- Do not rely on `signed_votes` method to get the votes
- Only count the voting power of a validator once (#335)
---
> Fix `VotingPowerCalculator::voting_power_in`

- CHANGES.md
- light-client/Cargo.toml
- light-node/Cargo.toml
- rpc/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/lib.rs
rendered changelog: https://github.com/informalsystems/tendermint-rs/blob/ismail/release/prep_v0.14.0/CHANGES.md#0140-2020-06-19
closes #344
> Prep v0.14.0 release

- rpc/Cargo.toml
Running into:
```
Compiling tendermint-rpc v0.14.0 (/Users/ismail/IdeaProjects/tendermint-rs/target/package/tendermint-rpc-0.14.0)
Finished dev [unoptimized + debuginfo] target(s) in 1m 10s
Uploading tendermint-rpc v0.14.0 (/Users/ismail/IdeaProjects/tendermint-rs/rpc)
error: api errors (status 200 OK): missing or empty metadata fields: license. Please see https://doc.rust-lang.org/cargo/reference/manifest.html for how to upload metadata
```
when trying to publish the rpc crate.
> add license meta data to rpc crate

- light-client/src/errors.rs
- light-client/src/peer_list.rs
- light-client/src/supervisor.rs
Neither list are currently used but have been added to match the spec more closely.
> Add list of spare and faulty nodes to PeerList

- README.md
As written now, licensed is only the README.md file itself. The license needs to be applied to the whole repository.
> Change Licence terms to all files in the Repo, not only README.md

- light-client/src/components/verifier.rs
- light-client/src/fork_detector.rs
- light-client/src/operations.rs
- light-client/src/operations/commit_validator.rs
- light-client/src/operations/hasher.rs
- light-client/src/operations/voting_power.rs
- light-client/src/predicates.rs
And rename the latter to just `Hasher`.
Close: #359
Ref: #342
> Move ValidatorSet::hash method over the HeaderHasher trait

- CHANGES.md
- tendermint/Cargo.toml
- tendermint/src/lib.rs
Cutting a small point release to get the following version bump for the KMS:
- Update `prost-amino`/`prost-amino-derive` to v0.6 ([#367])
[#367]: https://github.com/informalsystems/tendermint-rs/issues/367
> tendermint v0.14.1

- light-client/src/operations/commit_validator.rs
- light-client/src/predicates.rs
- light-client/src/predicates/errors.rs
> Refactor CommitValidator and port over code from the `lite_impl` module

- light-client/src/operations/voting_power.rs
See https://github.com/informalsystems/tendermint-rs/pull/306#discussion_r445121843
> Rename `untrusted_validators` param to `trusted_validators` in `check_enough_trust`

- light-client/src/components/scheduler.rs
See: #334
Should the items below can be split into their own issues, or discussed directly at #334?
---
> Simplify basic bisecting scheduler logic

- CHANGES.md
- light-client/src/errors.rs
- light-client/src/supervisor.rs
Part of #219 and preparation for #363. Wanted to split out the new additions to the light-client `Supervisor` and its `Handle` to make it easier to review and move forward. The declared goal of this change-set is to introduce new API to full-fill the planned endpoints of #219.
> light-client: expose latest_trusted on Supervisor Handle

- CHANGES.md
- light-client/examples/light_client.rs
- light-client/src/supervisor.rs
As we start to depend on the surface of the `Handle` we benefit from it being a trait that can be implemented on a per need basis. This will result in less overhead constructing object graphs in places where we want to assert behaviour of other types in remote places, i.e. the light-node RPC server. Overall we hope for an increased ease in writing tests on module level.
Ref #219
Ref #398
> light-client: turn Handle into a trait

- light-client/src/fork_detector.rs
- light-client/src/light_client.rs
- light-client/src/supervisor.rs
Update a few comments.
Rename `light_block -> verified_block` and `trusted_state -> trusted_block` to clarify the distinction during fork detection.
Also questions about:
- (re-) marking the trusted block as verified 
- reporting evidence to all peers
> Minor comment updates and var renames

- light-client/src/predicates.rs
This is coming up in automated integrations and in local tooling as
a warning. To reduce the noise it causes we remove the redundant field
assignment.
Ref: https://rust-lang.github.io/rust-clippy/master/#redundant_field_names
***
> chore: remove redundant field name

- tendermint/src/validator.rs
As discussed in #409, in order to maintain the type invariant of `validator::Set`, the validators are now sorted correctly also on deserializing the structure.
*NB! when migrating from v. 0.33 to 0.34, the sorting order in `sort_validators` function needs to be changed.*
> close #409: sort validators by address on deserialization

- rpc/tests/support/block_results.json
- tendermint/src/abci/responses.rs
- tendermint/src/serializers.rs
- tendermint/src/serializers/custom.rs
Fix rpc response deserialization issues. fix #423 
By the way, the `null_as_default` deserializer might be good to use on some other fields.
> abci: fix rpc response deserialization

- light-client/src/operations/hasher.rs
- rpc/tests/integration.rs
- rpc/tests/support/commit_1.json
- tendermint/src/lite_impl/header.rs
> Fix header.hash for height 1

- light-client/Cargo.toml
- rpc/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/account.rs
- tendermint/src/amino_types/ed25519.rs
- tendermint/src/config/node_key.rs
- tendermint/src/public_key.rs
- tendermint/src/validator.rs
> make dependency secp256k1 optional, fix #391

- CHANGES.md
- light-client/src/light_client.rs
- light-client/src/peer_list.rs
- light-client/src/store/memory.rs
- light-client/src/store/sled.rs
- light-client/src/supervisor.rs
- light-client/src/types.rs
- light-node/README.md
- light-node/src/commands/start.rs
- light-node/src/rpc.rs
https://github.com/informalsystems/tendermint-rs/issues/219#issuecomment-658041389
and contains a preliminary fix for #450 (thanks @OStevan)
closes #450 
closes #219
> light-client: add missing RPC endpoint and extend handler/supervisor

- rpc/tests/support/block_results.json
- tendermint/src/validator.rs
When removing validator, the power field is set to zero and ignored in json format.
> fix deserialize power field in validator_update

- light-client/Cargo.toml
Added backlink to repository and a description to light-client crate (pre publishing):
https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate
> light-client: minor changes in Cargo.toml (metadata)

- README.md
Main (top-level) Readme still says:
```
The following crates have not been published to crates.io yet:
light-client - Tendermint light client library for verifying signed headers, tracking validator set changes, and detecting forks
light-node - Tendermint light client binary
```
See: https://crates.io/crates/tendermint
Thanks for the heads up @andynog 🙏 
rendered: https://github.com/informalsystems/tendermint-rs/blob/ismail/fix_readme/README.md
> Fix readme: mention light-client / light-node as released

- light-client/src/peer_list.rs
- light-client/src/supervisor.rs
So user can see the real error for verification failure.
> Use primary error as context of `NoWitnessLeft` error

- light-client/src/predicates.rs
> fix predicate bug

- testgen/src/vote.rs
Trivial changes to make `Precommit` default for votes
> #491 testgen: make Precommit default vote type

- docs/spec/fastsync/fastsync.md
- docs/spec/lightclient/detection/detection.md
- docs/spec/lightclient/verification/verification.md
- tendermint/src/abci/transaction.rs
- tendermint/src/block.rs
- tendermint/src/block/commit.rs
- tendermint/src/block/header.rs
- tendermint/src/block/id.rs
- tendermint/src/evidence.rs
- tendermint/src/time.rs
- tendermint/src/vote.rs
This pr fixes broken links. 
There are a couple of links that lead to a file called `blockchain/fullnode.md` but this file doesn't exist. Not sure what it should be replaced with?
closes #492
> fix broken links

- light-client/tests/light_client.rs
- light-client/tests/supervisor.rs
- tendermint/src/merkle.rs
fixes https://github.com/informalsystems/tendermint-rs/issues/498
related golang changes: https://github.com/tendermint/tendermint/pull/5193
> merkle: return rfc6962 hash for empty merkle tree

- light-client/src/operations/voting_power.rs
- light-client/src/predicates/errors.rs
- tendermint/Cargo.toml
- tendermint/src/account.rs
- tendermint/src/amino_types/ed25519.rs
- tendermint/src/amino_types/proposal.rs
- tendermint/src/amino_types/signature.rs
- tendermint/src/amino_types/vote.rs
- tendermint/src/config/node_key.rs
- tendermint/src/lib.rs
- tendermint/src/node/id.rs
- tendermint/src/private_key.rs
- tendermint/src/public_key.rs
- tendermint/src/serializers/tests.rs
- tendermint/src/signature.rs
- tendermint/src/validator.rs
- tendermint/src/vote.rs
- testgen/Cargo.toml
- testgen/src/commit.rs
- testgen/src/helpers.rs
- testgen/src/validator.rs
- testgen/src/vote.rs
Native support for the `signature` traits used by the `signatory*` was recently added to `ed25519-dalek` in v1.0.0-pre.4, and the `k256` crate recently added a native pure Rust implementation of ECDSA/secp256k1.
Together these changes eliminate the need for the `signatory*` wrapper crates. Additionally, `k256` eliminates the need for the rust-secp256k1 C-based library, which has been problematic with e.g. WASM (#391).
This commit eliminates all `signatory` dependencies and uses `ed25519-dalek` and `k256` directly instead. Both of these were already dependencies, so it's not adding any additional dependencies, but instead removes several of them.
> Replace `signatory` with `ed25519-dalek` and `k256` crates

- light-client/Cargo.toml
- light-client/tests/light_client.rs
- light-client/tests/supervisor.rs
- testgen/src/lib.rs
- testgen/src/tester.rs
> Testgen tester

- docs/spec/lightclient/README.md
- docs/spec/lightclient/verification/verification.md
I fixed the two issues:
- some links inside the verification.md were broken
- the notation used in the table in README.md was not explained
> Fixes after comments on deliverable by Fernando

- tendermint/src/merkle.rs
Closes #538 
Reverting the identified commit turned out to be a hassle because of other changes that happened in testing since then.
Instead, I identified the actual change and created a commit that reverts the source code in the crucial place.
I left the newly created test in place, only I changed it to succeed in the current scenario.
If all goes well, this commit will be easier to revert in #540 after the v0.16 release
Note: the commit description falsely states v0.15 release. This is prepared for the v0.16 release.
No need for changelog update here, since this is reverting a new implementation to a previous - already expected - one.
> Revert empty Merkle tree hashing for v0.15 release

- CHANGELOG.md
- light-client/Cargo.toml
- light-client/src/lib.rs
- light-node/Cargo.toml
- light-node/src/lib.rs
- rpc/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/lib.rs
- testgen/Cargo.toml
Closes #93 
v0.16 release documents updated:
* CHANGELOG
* light-client, light-node and tendermint `lib.rs` version numbers
* light-client, light-node, rpc and tendermint `Cargo.toml`s
* testgen `Cargo.toml` tendermint dependencies
The rpc doesn't actually need a new release, if I was correct in parsing the commits. We only updated documentation. But it's nice to keep versioning together.
> CHANGELOG for v0.16, lib version updates

- .github/workflows/rust.yml
- light-client/src/predicates/errors.rs
- tendermint/src/block/commit_sig.rs
- testgen/src/tester.rs
Add the `--all-targets` flag to the invocation of Clippy in order to check all targets (standard, tests, examples and benchmarks).
---
Also renames the deprecated `--all` flag of `rustfmt` to `--workspace`.
---
> Run Clippy on all targets (standard, tests, examples and benchmarks)

- CHANGELOG.md
- tendermint/src/merkle.rs
Closes #540 .
Re-introduces the fix for empty Merkle tree hashing. This was created by Ismail before but it was pulled for the v0.16.0 release. We need it for 0.17.
> Empty Merkle tree hash fix

- light-node/src/rpc.rs
- testgen/src/commit.rs
It was getting a bit noisy (e.g. see: https://github.com/informalsystems/tendermint-rs/pull/571/files#diff-89fca07be889575fefb9e77a8de9051d)
This PR aims to fix all the open lints. An alternative way to get rid of the annotations but still keep clippy would be to call clippy in CI instead of using this action: https://github.com/actions-rs/clippy-check 
Note this only fixes a part (namely the clippy lints), not the compiler warnings which are a lot in e.g. `rpc/src/client/subscription.rs`. I assume this part will prob. improve with https://github.com/informalsystems/tendermint-rs/pull/572 as this means a major overhaul of the current subscription module anyways.
To reproduce the remaining warnings locally, run e.g.
`cargo test -p tendermint-light-client --test integration --no-fail-fast …
> Fix all clippy lints

- rpc/src/client.rs
- rpc/src/client/subscription.rs
- rpc/src/client/transport/mock/subscription.rs
- rpc/src/client/transport/websocket.rs
- rpc/src/event.rs
- tendermint/tests/integration.rs
In partial fulfillment of #568.
This adds an integration test to ensure that transaction subscription works (WebSocket-based subscription with query=`tm.event='Tx'`).
I had to make some fields in the relevant data structures optional, since they aren't always returned by the RPC remote endpoint.
> rpc: Fix and test WebSocket Tx event subscription

- testgen/jsonatr-lib/apalache_to_lite_test.json
- testgen/jsonatr-lib/unix.json
closes #587 
As discussed with @andrey-kuprianov, this command isn't really used anywhere except just to get it parsed into the existing `TestCase struct` from Conformance Tests. This is because MBT currently uses it to run tests with the existing test driver. We should eventually clean that up but this is a quick fix for now.
> Fix for running MBT on Macs

- rpc/tests/support/block_with_evidences.json
- tendermint/src/evidence.rs
Closes #502 
Doesn't seem like the `pub_key` field was used anywhere at all.
> Remove public key field from DuplicateVoteEvidence

- docs/spec/README.md
- docs/spec/fastsync/README.md
- docs/spec/fastsync/Tinychain.tla
- docs/spec/fastsync/fastsync.md
- docs/spec/fastsync/fastsync.tla
- docs/spec/fastsync/scheduler.tla
- docs/spec/lightclient/README.md
- docs/spec/lightclient/attacks/evidence-handling.md
- docs/spec/lightclient/detection/README.md
- docs/spec/lightclient/detection/detection.md
- docs/spec/lightclient/detection/discussions.md
- docs/spec/lightclient/detection/draft-functions.md
- docs/spec/lightclient/detection/req-ibc-detection.md
- docs/spec/lightclient/verification/Blockchain_A_1.tla
- docs/spec/lightclient/verification/Lightclient_A_1.tla
- docs/spec/lightclient/verification/verification.md
#594: I added a note to the files that they are not maintained and that the newer versions are in tendermint/spec.
@konnov : I did this for the main TLA+ files but not for each `MCx_y_bla.tla`. Is it OK?
> links to tendermint/spec

- testgen/jsonatr-lib/apalache_to_lite_test.json
- testgen/jsonatr-lib/unix.json
Reverting the previous quick fix for #587 (PR #593) and propagating the solution here from jsonatr (see [here](https://github.com/informalsystems/jsonatr/pull/11))
**What was the fix?** - modified the command argument so that it works uniformly on Linux and Mac
> MBT timestamp fix 

- tendermint/Cargo.toml
- tendermint/src/time.rs
A very long time ago this was used as a (monotonic, leap-second-free) internal representation for the `Time` type.
It was switched to use `chrono::DateTime<Utc>` and is now no longer needed.
> tendermint: remove `tai64` crate

- tendermint/src/abci/transaction.rs
Found myself wanting this today.
I imagine you could use similar impls throughout this crate, which allow you to do things like:
```rust
println!("tx: {:X}", tx);
```
> tendermint: impl fmt::UpperHex for abci::Transaction

- tendermint/src/abci/transaction.rs
The previous implementation would print hex strings like:
```
[FF, 1, FE, 2]
```
This changes the implementation to print the following instead (with test):
```
FF01FE02
```
> tendermint: improve fmt::UpperHex impl on Transaction

- tendermint/src/block/header.rs
This fixes the issue where deserialization of the header version fails when the `app` field is not supplied. We now explicitly supply the default value of 0 when the `app` field is not supplied.
> serialization: Supply default value for app version if field is missing in JSON

- tendermint/src/block/round.rs
- tendermint/src/consensus/state.rs
- tendermint/src/proposal.rs
- tendermint/src/vote/sign_vote.rs
Closes #628 
The same as with Height, we're introducing additional From traits for easier handling of the struct.
> Round struct From trait

- tendermint/src/public_key.rs
- tendermint/src/signature.rs
Fixes #626 .
This is a proposed fix for optional signatures.
> Added empty option to signature

- CHANGELOG.md
- rpc/src/endpoint/abci_query.rs
- rpc/src/endpoint/block.rs
- rpc/src/endpoint/block_results.rs
- rpc/src/endpoint/blockchain.rs
- rpc/src/endpoint/commit.rs
- rpc/src/endpoint/net_info.rs
- rpc/src/endpoint/validators.rs
> rpc: Expose RPC request/response fields publicly

- light-client/src/builder/supervisor.rs
- light-client/src/components/io.rs
- light-client/src/evidence.rs
- light-client/src/utils/block_on.rs
The `block_on` helper should be able to be used in cases where there are no peer id to speak of, eg. when blocking on a task which does not talk to a node over the network.
Additionally, this PR adds an option to the supervisor builder to configure the timeout for fork evidence submission.
> Remove `peer_id` parameter of `block_on` helper

- README.md
- proto/README.md
For the next v0.17.0-related release, we should probably bump these version numbers.
> docs: Update Tendermint/Rust versions in READMEs

- CHANGELOG.md
- light-client/src/predicates.rs
Close: #656
The change introduced in 355791f (as part of #652) enables DoS attacks, where full nodes could spam the light client with massive commits (eg. 10k validators).
See https://github.com/informalsystems/tendermint-rs/pull/652/commits/355791f2635a49aa82bbb5751a0e6f46bca94cf9#r515981617 for more info.
> Perform signers overlap check last

- CHANGELOG.md
- proto-compiler/src/constants.rs
- proto-compiler/src/functions.rs
Closes #660 
* Introduces a `find_reference_or_commit()` function to deal with tags, branches and commits together.
* Cleans up some of the function names and tries to make the code more readable.
> git_commitish now accepts commit IDs

- CHANGELOG.md
- light-client/Cargo.toml
- light-client/src/lib.rs
- light-node/Cargo.toml
- light-node/src/lib.rs
- proto/Cargo.toml
- proto/src/lib.rs
- rpc/Cargo.toml
- rpc/README.md
- rpc/src/lib.rs
- tendermint/Cargo.toml
- tendermint/src/lib.rs
- testgen/Cargo.toml
I've started updating the CHANGELOG for the v0.17.0-rc2 release.
📖 [Rendered CHANGELOG.md](https://github.com/informalsystems/tendermint-rs/blob/release/v0.17.0-rc2/CHANGELOG.md)
> Release v0.17.0-rc2

- testgen/Cargo.toml
- testgen/README.md
- testgen/src/lib.rs
`ibc-rs` is currently running into a dependency issue in https://github.com/informalsystems/ibc-rs/pull/390 due to the `tendermint-testgen` crate not being published on crates.io (see [`modules/Cargo.toml`](https://github.com/informalsystems/ibc-rs/blob/82476951668f4dc50006334ce1dbc1c13f0c719b/modules/Cargo.toml)).
We need to publish `tendermint-testgen` as a standalone crate to resolve this issue.
We don't have any crate documentation for testgen as of yet, but this can be remedied in a follow-up issue for the v0.17.0 release.
📖 [Rendered README](https://github.com/informalsystems/tendermint-rs/blob/testgen/publish/testgen/README.md)
> Allow testgen to be published to crates.io

- CHANGELOG.md
- light-client/Cargo.toml
Close: #425
We don't need Tokio when the `rpc-client` feature is not enabled, so let's only require it when this feature is enabled.
> light-client: Only require Tokio when `rpc-client` feature is enabled

- CHANGELOG.md
- light-client/Cargo.toml
- light-client/src/utils/block_on.rs
- light-node/Cargo.toml
- rpc-probe/Cargo.toml
- rpc-probe/src/error.rs
- rpc-probe/src/plan.rs
- rpc/Cargo.toml
- rpc/src/client/subscription.rs
- rpc/src/client/transport/http.rs
- rpc/src/client/transport/websocket.rs
- tendermint/Cargo.toml
- tendermint/tests/integration.rs
> Downgrade back to Tokio 0.2

- .github/workflows/test.yml
- docker/tendermint-v0.34.0/.gitignore
- docker/tendermint-v0.34.0/Dockerfile
- docker/tendermint-v0.34.0/entrypoint
Closes #702 .
Configuration to build tendermint docker images with default config. A few of these were built already with different versions of tendermint and uploaded to DockerHub here: https://hub.docker.com/repository/docker/informaldev/tendermint#
The integration tests were updated to run against a tendermint image close to "0.34.0-rc4" that was used in a previous Stargate testnet.
When upgrading Tendermint to be compatible with 034.0-rc5 (or later), we should also update these images to do proper integration testing.
> Added tendermint docker config

- release.sh
The current manual release process is a bit of a pain, so I thought I'd try to automate it just a tiny bit 😁 
From the documentation inside the script:
---
`release.sh` will hopefully allow us to publish all of the necessary crates in this repo in the right order, along with a few checks and balances to try to avoid mistakes. It is assumed that only one person will be releasing all crates at the same time.
For each crate, it will:
1. Run `cargo publish --dry-run` for that crate
2. List all files in the package with `cargo package --list`
3. Prompt the user as to whether to publish or not
4. Publish the package with `cargo publish` (no dry run)
It has a default set of crates it will publish, which can be overridden by
way of command line arguments:
```bash
./release.sh
./release.sh proto …
```
> Add basic release script

- p2p/Cargo.toml
"The policy so far's been to version all crates we intend to publish the
same such that "tendermint-rs" is versioned as a whole" - Thane.
> p2p: change version to 0.17.0-rc3

- p2p/README.md
- p2p/src/secret_connection/protocol.rs
Follows on from #715. We need a `README.md` in the crate before we can publish to crates.io.
> Release tendermint-p2p crate

- CHANGELOG.md
- proto/src/serializers/bytes.rs
- rpc/src/endpoint/broadcast/tx_commit.rs
- rpc/tests/parse_response.rs
- tendermint/src/abci/info.rs
- tendermint/src/abci/responses.rs
- tendermint/src/abci/tag.rs
> Automatically de/serialize ABCI event attributes from/to base64

- tendermint/Cargo.toml
Release notes: https://github.com/RustCrypto/elliptic-curves/pull/253
> Bump `k256` crate dependency to v0.6

- .cargo/config
- .github/workflows/build.yml
Small step toward #723 .
Introduces a few new cargo commands so that developers and the CI can easily run the same commands.
* `cargo build-all` == `cargo build --workspace --all-targets`
* `cargo build-wasm-tendermint` == (build tendermint with the wasm32-unknown-unknown target)
* `cargo build-wasm-light-client` == (build tendermint-light-client with the wasm32-unknown-unknown target)
This is a small example of how building and testing can be simplified between the developer and the CI. Further cases will come as I research the tools mentioned in #723.
Edit: it would be nice to have a simple `cargo build-wasm` command, but currently it's not possible, because the `--no-default-features` parameter cannot run in a virtual workspace, hence we need to add the `--manifest-path` parameter to …
> build optimizations

- .cargo/config
- .github/workflows/test.yml
Another harmonization effort for #723 : Made an alias for the `cargo test --all-features --no-fail-fast` command which parameters we usually use together. Now you can run `cargo test-all-features` with the same effect.
> Added cargo test-all-features

- CHANGELOG.md
- testgen/src/header.rs
- testgen/src/light_block.rs
- testgen/src/light_chain.rs
> testgen: Compute `last_block_id` hash when generating a light chain

- proto/src/serializers/timestamp.rs
- rpc-probe/src/kvstore.rs
- rpc-probe/src/quick.rs
- rpc/src/client.rs
- rpc/src/endpoint.rs
- rpc/src/endpoint/consensus_state.rs
- rpc/src/method.rs
- rpc/src/serialization.rs
- rpc/tests/parse_response.rs
- rpc/tests/support/consensus_state.json
- tendermint/src/hash.rs
- tendermint/src/serializers.rs
- tendermint/src/serializers/time.rs
- tendermint/src/time.rs
- tendermint/src/vote.rs
- tendermint/tests/integration.rs
> rpc: Add support for consensus_state endpoint

- tendermint/Cargo.toml
This is a minor bugfix release that required some breaking changes in the public API.
None of the bugs impact `tendermint-rs`, but it would be nice to ensure it's using the latest version before the final v0.17 release.
Release notes: https://github.com/RustCrypto/elliptic-curves/pull/261
> Bump `k256` crate dependency to v0.7

- CHANGELOG.md
- CONTRIBUTING.md
- light-client/Cargo.toml
- light-client/src/lib.rs
- light-client/src/supervisor.rs
- light-node/Cargo.toml
- light-node/src/lib.rs
- p2p/Cargo.toml
- proto/Cargo.toml
- proto/src/lib.rs
- release.sh
- rpc-probe/Cargo.toml
- rpc/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/hash.rs
- tendermint/src/lib.rs
- testgen/Cargo.toml
📖 [CHANGELOG](https://github.com/informalsystems/tendermint-rs/blob/release/v0.17.0/CHANGELOG.md#v0170)
📖 [New "Releases" section in contributing guidelines](https://github.com/informalsystems/tendermint-rs/blob/release/v0.17.0/CONTRIBUTING.md#releases)
> Release v0.17.0

- release.sh
We realized that we didn't have the `tendermint-p2p` crate in our release script.
> Add tendermint-p2p to release script

- CHANGELOG.md
- proto/src/serializers/timestamp.rs
- tendermint/src/time.rs
Close: #774 
The `Time` datatype needs to be formatted the same way as
Go's `time.RFC3339Nano` format, ie. a RFC3339 date-time
with left-padded nanoseconds digits without trailing zeros
and no trailing dot.
This is taken care of by the `to_rfc339_nanos` function in
the `tendermint_proto::serializers::timestamp` module.
Prior to this commit, this function would incorrectly
trim the leading zeros of the nanoseconds digits, which
would break the `Time` -> String -> `Time` roundtrip.
For example, the date "2021-01-07T17:52:04.034475Z" was serialized
as "2021-01-07T17:52:04.34475Z", which then decodes to
"2021-01-07T17:52:04.344750Z", shifting the leading zero to the end.
This commit fixes `to_rfc339_nanos` function by using `chrono`'s
formatting facilities to preserve the precision of the …
> Fix formatting of tendermint::Time values

- CHANGELOG.md
- light-client/Cargo.toml
- light-client/examples/light_client.rs
- light-client/src/store.rs
- light-client/src/store/sled.rs
- light-node/Cargo.toml
- light-node/src/commands/initialize.rs
- light-node/src/commands/start.rs
See: https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452745330
> Feature-guard the sled light store and hide the dependency on sled

- CHANGELOG.md
- light-client/Cargo.toml
- light-client/examples/light_client.rs
- light-client/src/store.rs
- light-client/src/store/sled.rs
- light-node/Cargo.toml
- light-node/src/commands/initialize.rs
- light-node/src/commands/start.rs
See: https://github.com/informalsystems/tendermint-rs/pull/430#discussion_r452745330
> Feature-guard the sled light store and make the dependency on sled internal

- light-client/src/supervisor.rs
Minor fix. This came up in [CI](https://github.com/informalsystems/tendermint-rs/runs/1783894688) as well as while trying to test out the commands in #790.
> Fix missing hasher parameter for supervisor test

- light-client/README.md
- light-client/tests/model_based.rs
- light-client/tests/support/model_based/README.md
This PR address one TODO left in #787. It also adds back the instructions on how to install `tendermint-testgen` as the binary is in fact used, for example, in [here](https://github.com/informalsystems/tendermint-rs/blob/master/testgen/jsonatr-lib/tendermint.json#L8) (and thus, [this comment](https://github.com/informalsystems/tendermint-rs/pull/787#issuecomment-767473703) is wrong). Thanks @Shivani912 for pointing it out and for the help addressing the TODO.
> Improve light-client README

- p2p/src/secret_connection.rs
Split SecretConnection::new into 3 states:
- new (_no separate state really_)
- awaiting ephemeral key (`AwaitingEphKey`)
- awaiting auth signature (`AwaitingAuthSig`)
First, you need to use Handshake::new to create a Handshake state
machine (STM), which is immediately put into AwaitingEphKey state.
When you obtain a remote ephemeral key, you're supposed to call
`got_key` fn to transition STM to the next state - `AwaitingAuthSig`.
NOTE: Handshake does not do IO and does not care how exchange is done.
Once you have the remote auth signature, you're supposed to call
`got_signature` fn, which returns the final piece - remote pubkey.
The construction of `SecretConnection` is now complete.
Closes #735
> p2p: apply state machine pattern when building SecretConnection

- tendermint/Cargo.toml
- tendermint/proptest-regressions/time.txt
- tendermint/src/time.rs
This is an initial effort towards adding an extensible foundation for PBT, as per #303.
The main intents of this contribution are:
- Evaluate whether PBT will add value to our test harness.
- Begin to establish a library of combinators for generating elementary arbitrary values (it is no accident that we begin with a combinators for time).
- Add generators for arbitrary RFC3339 timestamps (as strings) and `DateTime<Utc>` structs (including within a specified range). These will be generally useful in PBT tests, any time we need to construct objects that contain time structs or timestamps. In a followup, I expect these strategies will be moved into their own library that can be used in different tests, which will considerably reduce the the amount of code in the test here. So the amount of …
> Property based tests of Time

- Cargo.toml
- pbt-gen/Cargo.toml
- pbt-gen/README.md
- pbt-gen/src/lib.rs
- pbt-gen/src/time.rs
- tendermint/Cargo.toml
- tendermint/src/time.rs
Closes #828
This allows us to use the timestamp and DateTime generators in any other
crate in our workspace. It should help advance #822 and #821.
-------
> Move time proptest generators into their own crate

- CHANGELOG.md
- light-client/src/operations/commit_validator.rs
- light-client/src/operations/voting_power.rs
- light-client/src/predicates.rs
- light-client/src/store/sled.rs
- light-client/src/supervisor.rs
- light-client/tests/backward.rs
- light-client/tests/model_based.rs
- p2p/src/secret_connection.rs
- p2p/src/secret_connection/protocol.rs
- rpc/src/event.rs
- tendermint/src/abci/gas.rs
- tendermint/src/account.rs
- tendermint/src/block/commit_sig.rs
- tendermint/src/block/header.rs
- tendermint/src/block/height.rs
- tendermint/src/block/round.rs
- tendermint/src/config.rs
- tendermint/src/genesis.rs
- tendermint/src/validator.rs
- testgen/src/commit.rs
- testgen/src/light_block.rs
- testgen/src/validator.rs
Rust's [1.51 release](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html) brought with it a number of new clippy errors and warnings. This PR attempts to address the bulk of them.
Unfortunately this results in some breaking changes to data structures' names, because they were improperly named up to now according to Rust's API guidelines.
> Fix clippy errors/warnings when upgrading to Rust 1.51

- .github/workflows/test.yml
Closes #843 
The test's still most likely going to be valuable, but just not on each PR necessarily.
> Remove kvstore-integration-latest test from CI

- .github/workflows/audit.yml
It appears as though the indentation of the scheduling config was off by one level, causing GitHub Actions to ignore it.
> Fix scheduled audit job in CI

- .github/actions-rs/grcov.yml
- .github/workflows/test.yml
With this PR, we start tracking coverage using LLVM's source-based coverage: https://blog.rust-lang.org/inside-rust/2020/11/12/source-based-code-coverage.html
- pin nightly version to avoid spurious errors (it's unlikely we need to bump this often, unless we need new compiler features)
- pin grcov version to avoid https://github.com/mozilla/grcov/issues/555
- set `LLVM_PROFILE_FILE="%m.profraw"` to avoid overwrites of coverage data (which occur when several test binaries are run for the same crate): https://github.com/rust-lang/rust/issues/79899
- maybe the 30% coverage decreases (https://github.com/informalsystems/tendermint-rs/pull/839#issuecomment-807115109 and https://github.com/informalsystems/tendermint-rs/issues/252#issuecomment-805623519) are due to something like this
With this, …
> Source-based coverage

- CHANGELOG.md
- rpc/src/endpoint/consensus_state.rs
> Fix consensus state vote summary deserialization

- rpc/src/client.rs
Adds a method which repeatedly polls the `/health` endpoint until it returns a successful response or a specified timeout elapses.
This is useful when writing tests that need to wait for a node to boot up (e.g. inside of a docker container), e.g.:
https://github.com/cosmos/cosmos-rust/pull/71/files#diff-0e31f23fc223d1d543169a682e0f1093c1cc53c6a312febce7d5d1854919fafaR84-R96
> rpc: add `Client::wait_until_healthy` method

- p2p/Cargo.toml
- p2p/src/lib.rs
- p2p/src/secret_connection.rs
- p2p/src/secret_connection/pipe.rs
Closes #841
A copy of the `pipe` crate (https://github.com/arcnmx/pipe-rs) is added to the `tendermint-p2p` crate. I had to add a new method - `async_bipipe_buffered` to make the handshake tests always pass. `async_bipipe_buffered` method uses the `unbounded` channel (rather than the blocking one) for communication - hence the prefix. Note I also removed the methods and structures from `pipe` clone that we're not using at the moment.
> p2p: use async bipipe

- rpc/src/client.rs
- rpc/src/endpoint.rs
- rpc/src/endpoint/tx.rs
- rpc/src/endpoint/tx_search.rs
- rpc/src/method.rs
- rpc/tests/parse_response.rs
- rpc/tests/support/tx_no_prove.json
- rpc/tests/support/tx_with_prove.json
- tools/kvstore-test/tests/tendermint.rs
Support for finding a transaction directly by its hash.
In theory this endpoint should have read-your-writes (RYW) consistency whereas `/tx_search` does not.
See: https://github.com/tendermint/tendermint/issues/6359
> rpc: add support for `/tx` endpoint

- tendermint/Cargo.toml
Bumps `k256` to the latest release.
It seems like some refactoring of the public keys might be in order at this point, but I decided to start with a simple version bump.
I could also potentially add NIST P-256 support with the `p256` crate too.
> Bump `k256` crate dependency to v0.8

- light-client/tests/support/model_based/Blockchain_003_draft.tla
- light-client/tests/support/model_based/LightTests.tla
- light-client/tests/support/model_based/Lightclient_003_draft.tla
- light-client/tests/support/model_based/MC4_4_faulty.tla
In order to make use of the latest Apalache for MBT, we need to update the typing to use the current annotation practice.
Discussed with @andrey-kuprianov and @konnov via Slack.
> Update the TLA specs used in MBT with the current Apalache type annotations

- abci/Cargo.toml
- light-client-js/Cargo.toml
- light-client/Cargo.toml
- p2p/Cargo.toml
- pbt-gen/Cargo.toml
- rpc/Cargo.toml
- testgen/Cargo.toml
At present, the code in #708 produces a number of clippy errors due to missing metadata in crates' `Cargo.toml` files, e.g.
```
error: package `tendermint-abci` is missing `package.categories` metadata
|
= note: `-D clippy::cargo-common-metadata` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cargo_common_metadata
```
This adds the missing metadata and appeases clippy. We should just verify that the keywords/categories I've added here are appropriate.
> p2p: Update crates' metadata to address clippy errors

- .changelog/README.md
- .changelog/epilogue.md
- .changelog/unreleased/bug-fixes/876-delivertx.md
- .changelog/unreleased/improvements/891-changelog.md
- .changelog/unreleased/removed/879-rm-light-node.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
As per out-of-band discussions, we noticed that we often end up in a situation where we're working on several PRs simultaneously, each of which modifies the `CHANGELOG.md` file but makes changes to distinct parts of the code base. This inevitably results in annoying merge conflicts purely related to the changelog.
The simplest solution seems to be to disaggregate changelog entries and build `CHANGELOG.md` from those entries as we perform a release.
For this, I built [unclog](https://github.com/informalsystems/unclog), which is a small CLI tool written in Rust, to help manage these disaggregated changelog entries.
> Switch to `unclog` to parallelize changelog updates

- .changelog/unreleased/improvements/851-tempdir.md
- CHANGELOG.md
- light-client/Cargo.toml
- light-client/src/store/sled.rs
- light-client/src/store/sled/utils.rs
- tools/proto-compiler/Cargo.toml
- tools/proto-compiler/src/main.rs
> Replace `tempdir` dependency with `tempfile`

- tendermint/Cargo.toml
As discussed in #892.
This release makes `bitvec` an optional dependency (gated under the `bits` feature). Since tendermint-rs doesn't need it at all, it's disabled as per default. This eliminates some transitive dependencies, which I know have been a problem in the past (#816).
The internal implementation is now using const generics, so this crate has a MSRV of 1.51+.
> Bump `k256` crate dependency to v0.9; MSRV 1.51+

- p2p/Cargo.toml
It appears v0.10.6 does not build on stable Rust:
https://github.com/zesterer/flume/issues/83
This works around the issue
> p2p: pin `flume` to v0.10.5

- .changelog/unreleased/improvements/900-secp256k1-public-keys.md
- tendermint/src/account.rs
- tendermint/src/public_key.rs
- tendermint/src/validator.rs
See #873 for background.
This changes the type re-exported as `tendermint::public_key::Secp256k1` from a `k256::EncodedPoint` to a `k256::ecdsa::VerifyingKey`.
The main distinction this provides is validating the public key (i.e. making sure it provides a valid solution to the secp256k1 curve equation), whereas `EncodedPoint` provides no validation of the public key.
If there were ever a `Signature::Secp256k1` variant added, this would also make it easy to perform signature verification.
> tendermint: use k256::ecdsa::VerifyingKey as Secp256k1 key

- tendermint/src/error.rs
- tendermint/src/node/id.rs
Convenience to obtain a `node::Id` from a PublicKey, which is especially
useful in the context p2p and protocols built on top of it as the main
reference a peer is catalogued by is the `node::Id`.
> tendermint: Add TryFrom for node::Id from PublicKey

- docs/architecture/adr-009-transport-agnostic-peer-abstraction.md
- p2p/src/lib.rs
- p2p/src/transport.rs
Describes broadly a new set of abstractions to support a transport
agnostic p2p stack. Bundled together are the types and traits in
`p2p::transport`. Other parts like the `Supervisor` will land in
follow-up change-sets.
Closes #692
***
[Rendered ADR-009](https://github.com/informalsystems/tendermint-rs/blob/xla/692-p2p-transport/docs/architecture/adr-009-transport-agnostic-peer-abstraction.md)
Supersedes #708
> p2p: Propose transport agnostic abstractions

- .changelog/unreleased/bug-fixes/908-config-opt-values.md
- tendermint/Cargo.toml
- tendermint/src/config.rs
- tendermint/src/net.rs
- tendermint/src/timeout.rs
- tendermint/tests/config.rs
> Tendermint config handle optional values + fix `net::Address` Display

- .changelog/unreleased/breaking-changes/909-self-conventions.md
- light-client/Cargo.toml
- light-client/src/supervisor.rs
- proto/src/serializers/timestamp.rs
- proto/tests/unit.rs
- rpc/Cargo.toml
- rpc/src/endpoint/consensus_state.rs
- rpc/tests/parse_response.rs
- tendermint/src/public_key.rs
- tendermint/src/serializers/time.rs
- tendermint/src/signature.rs
- tendermint/src/time.rs
- tendermint/src/vote.rs
- tendermint/src/vote/power.rs
- test/src/pipe.rs
- test/src/test/unit/p2p/secret_connection.rs
> Fix latest clippy assertion failures

- p2p/Cargo.toml
> p2p: Bump chacha20poly1305 dependency

- .github/workflows/rust.yml
- light-client/Cargo.toml
- rpc/Cargo.toml
Closes #911 
Seems like we were using the wrong environment variable in CI: https://github.com/tokio-rs/tokio/issues/3880#issuecomment-866056546
> Unpin Tokio version and fix docs test in CI

- .changelog/unreleased/improvements/871-rebuild-protobuf.md
- proto/src/prost/google.protobuf.rs
- proto/src/prost/tendermint.abci.rs
- proto/src/prost/tendermint.blockchain.rs
- proto/src/prost/tendermint.consensus.rs
- proto/src/prost/tendermint.crypto.rs
- proto/src/prost/tendermint.libs.bits.rs
- proto/src/prost/tendermint.mempool.rs
- proto/src/prost/tendermint.p2p.rs
- proto/src/prost/tendermint.privval.rs
- proto/src/prost/tendermint.rpc.grpc.rs
- proto/src/prost/tendermint.state.rs
- proto/src/prost/tendermint.statesync.rs
- proto/src/prost/tendermint.types.rs
- proto/src/prost/tendermint.version.rs
- proto/src/tendermint.rs
- tools/proto-compiler/src/constants.rs
Closes #871 
Additionally just updates `tendermint-rs` to ensure compatibility with the latest released version of Gaia. I've given the (automatically produced) changes a once-over and it doesn't look like there are any meaningful changes.
If so, then this PR effectively just reduces the noise for any future rebuilds of the serialization types to make those changes easier to see.
> Rebuild Protobuf data structures for Tendermint v0.34.9

- .changelog/unreleased/bug-fixes/917-update-tendermint-genesis.md
- light-client/src/operations/voting_power.rs
- rpc/tests/kvstore_fixtures.rs
- rpc/tests/parse_response.rs
- rpc/tests/support/genesis.json
- tendermint/src/block/size.rs
- tendermint/src/genesis.rs
- tendermint/src/validator.rs
- testgen/src/consensus.rs
- testgen/src/validator.rs
- tools/kvstore-test/tests/tendermint.rs
> update Tendermint genesis

- .changelog/unreleased/improvements/919-rpc-url-bounds.md
- rpc/src/client/transport/http.rs
- rpc/src/client/transport/websocket.rs
- rpc/src/rpc_url.rs
> Add equality/ordering/hash trait bounds to RPC URL types

- .changelog/unreleased/improvements/925-timestamp-conversion.md
- abci/Cargo.toml
- p2p/Cargo.toml
- proto/Cargo.toml
- proto/src/prost/tendermint.crypto.rs
- proto/src/prost/tendermint.p2p.rs
- proto/src/prost/tendermint.types.rs
- proto/src/tendermint.rs
- tendermint/Cargo.toml
- tendermint/src/time.rs
> Update `prost` and `prost-types` to version 0.8

- .changelog/unreleased/breaking-changes/918-dedup-domaintypes.md
- rpc/src/event.rs
- rpc/tests/kvstore_fixtures.rs
- tendermint/src/abci/responses.rs
> Deduplicate RPC domain types

- .changelog/unreleased/breaking-changes/924-trust-threshold.md
- light-client/src/operations/voting_power.rs
- tendermint/src/error.rs
- tendermint/src/trust_threshold.rs
- tools/kvstore-test/tests/light-client.rs
- tools/kvstore-test/tests/tendermint.rs
> Ensure correct `TrustThresholdFraction` construction

- Cargo.toml
- light-client-js/Cargo.toml
I believe that the "blessed" way to add profile settings in Cargo workspaces is with package overrides now
- [Cargo Documentation](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides)
- [Stack Overflow Thread](https://stackoverflow.com/questions/45794917/specific-profiles-for-workspace-members)
I was getting warnings when building which suggested that the profile setting in `light-client-js` wasn't doing anything because profiles need to be set on the project manifest.
> Fix Warning in Cargo Build

- .changelog/unreleased/breaking-changes/923-flex-error.md
> Add changelog entry for flex-error integration work

- .changelog/unreleased/improvements/814-clonable-secret-conn.md
- Cargo.toml
- p2p/Cargo.toml
- p2p/src/secret_connection.rs
- p2p/src/transport.rs
- release.sh
- std-ext/Cargo.toml
- std-ext/README.md
- std-ext/src/lib.rs
- std-ext/src/try_clone.rs
- test/src/test/unit/p2p/secret_connection.rs
Work towards #814 
Something like this is necessary for the MConnection to be able to safely read from and write to the underlying stream from multiple threads (e.g. one thread for reading, one thread for writing).
> Implement full-duplex secret connection

- light-client/src/components/verifier.rs
- light-client/src/evidence.rs
- light-client/src/macros.rs
- light-client/src/peer_list.rs
- light-client/src/predicates.rs
- light-client/src/store/memory.rs
- light-client/src/supervisor.rs
- tendermint/src/abci/tag.rs
- tendermint/src/chain/id.rs
- testgen/src/tester.rs
- testgen/src/validator_set.rs
Some new clippy errors have appeared recently on `master` (most likely due to upgrading to Rust 1.54). This PR aims to fix them.
See https://github.com/informalsystems/tendermint-rs/runs/3242281271
> Fix recent clippy errors on `master`

- .changelog/unreleased/improvements/814-clonable-secret-conn.md
- Cargo.toml
- light-client/src/components/verifier.rs
- light-client/src/macros.rs
- light-client/src/peer_list.rs
- light-client/src/predicates.rs
- light-client/src/store/memory.rs
- light-client/src/supervisor.rs
- p2p/Cargo.toml
- p2p/src/error.rs
- p2p/src/secret_connection.rs
- p2p/src/transport.rs
- release.sh
- std-ext/Cargo.toml
- std-ext/README.md
- std-ext/src/lib.rs
- std-ext/src/try_clone.rs
- tendermint/src/abci/tag.rs
- tendermint/src/chain/id.rs
- test/Cargo.toml
- test/src/test/unit/p2p/secret_connection.rs
- testgen/src/tester.rs
- testgen/src/validator_set.rs
> flex-error: resolve conflicts with `master`

- .changelog/unreleased/breaking-changes/942-rpc-tx-hash-field.md
- .changelog/unreleased/bug-fixes/942-rpc-tx-encoding.md
- rpc/src/client/bin/main.rs
- rpc/src/endpoint/tx.rs
- rpc/src/endpoint/tx_search.rs
- rpc/tests/kvstore_fixtures.rs
- rpc/tests/kvstore_fixtures/incoming/tx.json
- rpc/tests/kvstore_fixtures/outgoing/tx.json
- tendermint/src/abci/transaction.rs
- tendermint/src/abci/transaction/hash.rs
- tendermint/src/serializers.rs
- tendermint/src/serializers/hash_base64.rs
- tools/kvstore-test/tests/tendermint.rs
> Change `hash` parameter of `/tx` RPC endpoint encoding to base64

- .changelog/unreleased/improvements/969-derive-eq-signed-header-commit.md
- rpc/src/endpoint/abci_query.rs
- rpc/src/error.rs
- tendermint/src/block/commit.rs
- tendermint/src/block/commit_sig.rs
- tendermint/src/block/header.rs
- tendermint/src/block/signed_header.rs
- tendermint/src/error.rs
- tendermint/src/hash.rs
- tendermint/src/signature.rs
- tendermint/src/validator.rs
> Derive `PartialEq` and `Eq` on more types

- .changelog/config.toml
- .changelog/unreleased/features/832-consensus-params.md
- rpc/src/client.rs
- rpc/src/client/bin/main.rs
- rpc/src/endpoint.rs
- rpc/src/endpoint/consensus_params.rs
- rpc/src/method.rs
- rpc/tests/kvstore_fixtures.rs
- rpc/tests/kvstore_fixtures/incoming/consensus_params.json
- rpc/tests/kvstore_fixtures/outgoing/consensus_params.json
- tools/kvstore-test/tests/tendermint.rs
- tools/rpc-probe/src/kvstore.rs
- tools/rpc-probe/src/quick.rs
Partial fulfillment of #832, and helps towards https://github.com/informalsystems/ibc-rs/issues/1336
> Add `/consensus_params` RPC endpoint

- .changelog/unreleased/breaking-changes/disable-sled-lightstore.md
- light-client/Cargo.toml
- light-client/examples/light_client.rs
> light-client: Disable `lightstore-sled` feature by default

- .changelog/unreleased/improvements/ws-config.md
- rpc/src/client.rs
- rpc/src/client/transport/websocket.rs
- rpc/src/lib.rs
Closes: #974
This PR directly re-exports the `tungstenite::protocol::WebSocketConfig`. We could also define our own config type and convert it into the former if that's deemed preferable.
> Add `WebSocketClient::new_with_config` to specify the WebSocket connection settings

- .changelog/config.toml
- .changelog/unreleased/improvements/968-mbt.md
- light-client/Cargo.toml
- light-client/tests/model_based.rs
> Disable Light Client model-based tests by default

- .changelog/unreleased/breaking-changes/956-light-client-predicates-ibc.md
- light-client-js/src/lib.rs
- light-client/src/builder/light_client.rs
- light-client/src/components/verifier.rs
- light-client/src/light_client.rs
- light-client/src/operations/commit_validator.rs
- light-client/src/operations/hasher.rs
- light-client/src/operations/voting_power.rs
- light-client/src/predicates.rs
- light-client/src/tests.rs
- light-client/src/types.rs
- tendermint/src/block/signed_header.rs
- tendermint/src/error.rs
Closes #956 
The main aim of this PR is to remove references to the `LightBlock` type from the verification predicates, as the `LightBlock` type isn't used in https://github.com/informalsystems/ibc-rs/pull/1252
Tomorrow I'll try working on refactoring that PR to make use of this code to see if it will work.
> Refactor Light Client verification predicates interface for use from IBC

- light-client/src/store/sled.rs
- light-client/src/supervisor.rs
- light-client/src/tests.rs
- light-client/tests/backward.rs
- light-client/tests/light_client.rs
- light-client/tests/supervisor.rs
In working towards #978, some new clippy errors are popping up in CI with the latest Rust nightly. See https://github.com/informalsystems/tendermint-rs/pull/978/checks?check_run_id=3635238166 for an example.
This PR attempts to address these errors. If acceptable, I'll merge to `master` and then pull these changes into #978.
> Fix nightly clippy errors 

- .github/workflows/test.yml
- abci/src/application/kvstore.rs
- abci/src/lib.rs
- rpc/Cargo.toml
- rpc/src/client/transport/mock.rs
> Fix `cargo test` and add check to CI

- .changelog/unreleased/features/832-block-search.md
- rpc/src/client.rs
- rpc/src/client/bin/main.rs
- rpc/src/endpoint.rs
- rpc/src/endpoint/block_search.rs
- rpc/src/method.rs
- rpc/tests/kvstore_fixtures.rs
- rpc/tests/kvstore_fixtures/incoming/block_search.json
- rpc/tests/kvstore_fixtures/outgoing/block_search.json
- tools/kvstore-test/tests/tendermint.rs
- tools/rpc-probe/src/quick.rs
> Add `block_search` RPC endpoint

- .github/workflows/test.yml
- tools/kvstore-test/Makefile.toml
- tools/kvstore-test/tests/tendermint.rs
> tools: Fix `block_search` endpoint integration tests

- light-client/Cargo.toml
- light-client/src/components/clock.rs
- light-client/src/components/verifier.rs
- light-client/src/contracts.rs
- light-client/src/predicates.rs
- light-client/src/predicates/errors.rs
- light-client/src/supervisor.rs
- light-client/tests/backward.rs
- light-client/tests/model_based.rs
- proto/Cargo.toml
- tendermint/src/block/commit_sig.rs
- tendermint/src/block/header.rs
- tendermint/src/error.rs
- tendermint/src/evidence.rs
- tendermint/src/proposal.rs
- tendermint/src/proposal/canonical_proposal.rs
- tendermint/src/time.rs
- tendermint/src/vote.rs
- tendermint/src/vote/canonical_vote.rs
- testgen/Cargo.toml
- testgen/src/header.rs
- testgen/src/helpers.rs
- testgen/src/time.rs
- testgen/src/vote.rs
Part of informalsystems/ibc-rs#1158. This is a succession of #980
This PR removes the use of `std::time::SystemTime` and replace them with `chrono::DateTime` so that the `tendermint` crate can be no_std compliant.
> Use chrono::DateTime instead of std::time::SystemTime

- .changelog/unreleased/bug-fixes/1016-lowercase-node-id.md
- config/tests/mod.rs
- tendermint/src/node/id.rs
- test/src/test/unit/p2p/secret_connection/public_key.rs
> lowercase hex node ID

- .github/workflows/test.yml
Follows from https://github.com/informalsystems/tendermint-rs/pull/862#discussion_r739678015
We could just go back to using `nightly`, but then we open ourselves up to arbitrary CI breakage.
> ci: Update coverage check

- .changelog/unreleased/improvements/1023-ed25519-deprecations.md
- tendermint/Cargo.toml
- tendermint/src/proposal.rs
- tendermint/src/signature.rs
- tendermint/src/test.rs
- tendermint/src/vote.rs
- tendermint/src/vote/sign_vote.rs
- testgen/src/vote.rs
Fixes: #1023
As of release 1.3.0, `ed25519` deprecates the standalone `SIGNATURE_LENGTH` constant in favor of the `Signature::BYTE_SIZE` associated item. Also, the `Signature::new` constructor is deprecated in favor of `Signature::from_bytes`.
Update the code to not trigger the deprecation lints.
In turn, deprecate what was formerly the reexport of that constant in the tendermint API.
> Update to deprecations in ed25519 1.3

- .changelog/unreleased/improvements/1023-ed25519-deprecations.md
- tendermint/Cargo.toml
- tendermint/src/proposal.rs
- tendermint/src/signature.rs
- tendermint/src/test.rs
- tendermint/src/vote.rs
- tendermint/src/vote/sign_vote.rs
- testgen/src/vote.rs
> Update to deprecations in ed25519 1.3 (backport to 0.23.x)

- tendermint/src/signature.rs
0.23.1 was released before #1023 or its backport to v0.23.x (#1031) were merged.
> Fix up deprecation version for ED25519_SIGNATURE_SIZE

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/architecture/README.md
- docs/architecture/adr-template.md
Related to #1018.
This PR updates the repo documentation (README, contributing guidelines, ADR docs, PR and issue templates) to (1) better reflect how we currently work, and (2) accommodate the new versioning approach.
Note that I've taken out the RFC-related documentation from the contributing guidelines because we don't do RFCs. I think it complicates the contributing guidelines as well.
Rendered versions:
- [README](https://github.com/informalsystems/tendermint-rs/blob/thane/repo-admin/README.md)
- [Contributing guidelines](https://github.com/informalsystems/tendermint-rs/blob/thane/repo-admin/CONTRIBUTING.md)
- [ADR README](https://github.com/informalsystems/tendermint-rs/blob/thane/repo-admin/docs/architecture/README.md)
> Update docs and repo config for new versioning approach

- .changelog/unreleased/breaking-changes/1040-rpc-remove-server-error.md
- rpc/src/error.rs
This does not seem to be produced anywhere.
Fixes: #1039
* ~Updated all code comments where relevant~
* ~Wrote tests~
> rpc: Remove ErrorDetail::Server

- docs/architecture/adr-010-time-api-sanity.md
Proposes changes to time API in `tendermint` and some related improvements that would be good to do in a tranche of breaking changes.
> ADR: Time API improvements

- .changelog/unreleased/breaking-changes/1041-box-large-fields-in-enums.md
- abci/src/application/echo.rs
- light-client/src/fork_detector.rs
- rpc/src/abci/info.rs
- rpc/src/abci/responses.rs
- rpc/src/client/transport/mock.rs
- rpc/src/client/transport/router.rs
- rpc/src/endpoint/validators.rs
- rpc/src/event.rs
- tendermint/src/block/round.rs
- tendermint/src/evidence.rs
- testgen/src/tester.rs
The new lints pop up in the CI for multiple PRs.
* ~Wrote tests~
> Fix lints reported by clippy 0.1.57

- abci/src/application/echo.rs
- light-client/src/fork_detector.rs
- rpc/src/client/transport/mock.rs
- rpc/src/client/transport/router.rs
- rpc/src/endpoint/validators.rs
- rpc/src/event.rs
- tendermint/src/abci/info.rs
- tendermint/src/abci/responses.rs
- tendermint/src/block/round.rs
- tendermint/src/evidence.rs
- testgen/src/tester.rs
Backport of #1041 to v0.23.x
Overrides `clippy::large_enum_variant` instead of changing the enums.
> Fix clippy 0.1.57 lints (backport to 0.23.x)

- .changelog/unreleased/breaking-changes/1030-remove-chrono.md
- .changelog/unreleased/improvements/1030-new-time-api.md
- light-client/Cargo.toml
- light-client/src/components/clock.rs
- light-client/src/predicates.rs
- light-client/tests/model_based.rs
- pbt-gen/Cargo.toml
- pbt-gen/src/time.rs
- proto/Cargo.toml
- proto/src/serializers/timestamp.rs
- rpc/Cargo.toml
- rpc/src/endpoint/consensus_state.rs
- rpc/src/query.rs
- rpc/tests/parse_response.rs
- tendermint/Cargo.toml
- tendermint/src/error.rs
- tendermint/src/proposal.rs
- tendermint/src/serializers/time.rs
- tendermint/src/time.rs
- tendermint/src/vote/sign_vote.rs
- testgen/Cargo.toml
- testgen/src/header.rs
- testgen/src/lib.rs
> Replace chrono with time 0.3 (backport to 0.23.x)

- .github/workflows/build.yml
- .github/workflows/rust.yml
- .github/workflows/test.yml
At present, it appears as though our workflows don't run when we merge to version-specific branches like `v0.23.x`. This attempts to fix that.
> Execute CI workflows on version-specific branches

- .changelog/unreleased/improvements/1030-new-time-api.md
- light-client/src/predicates.rs
- pbt-gen/Cargo.toml
- tendermint/src/time.rs
Fixes: #1047
Do not require time 0.3.5, because ibc-rs has another dependency that
pins time at =0.3.2.
This means the recently added methods `Time::checked_add` and
`Time::checked_sub` have to be removed. Fortunately, they haven't made it
into a 0.23.x release yet.
* ~Wrote tests~
> Roll back time-rs dependency and remove methods that require version 0.3.5

- light-client/Cargo.toml
- proto/Cargo.toml
- rpc/Cargo.toml
- tendermint/Cargo.toml
- testgen/Cargo.toml
tendermint uses `checked_add`/`checked_sub` methods which were added
in time 0.3.5.
See also #1048 for the v0.23.x branch.
* ~Updated all code comments where relevant~
* ~Wrote tests~
* ~Added entry in `.changelog/`~
> Bump time dependency version to 0.3.5

- config/Cargo.toml
- light-client/Cargo.toml
- tendermint/Cargo.toml
> Remove unnecessary cdylib artifacts from the build

- .changelog/unreleased/improvements/1054-derive-hash-on-time.md
- tendermint/src/time.rs
Now that we're backed by a data structure with unambiguously unique values, we can make time moments hashable.
* ~Updated all code comments where relevant~
> Derive `Hash` on `tendermint::Time`

- .changelog/unreleased/improvements/1054-derive-hash-on-time.md
- tendermint/src/time.rs
> backport: Derive `Hash` on `tendermint::Time`

- tendermint/Cargo.toml
Updates `k256` crate to the latest version.
Release notes: https://github.com/RustCrypto/elliptic-curves/pull/485
> Bump `k256` to v0.10

- tendermint/Cargo.toml
Backport of #1059 for v0.23.x.
> backport: Bump `k256` to v0.10 (#1059)

- .changelog/unreleased/breaking-changes/1046-p2p-ed25519-consensus.md
- .changelog/unreleased/dependencies/1046-ed25519-consensus-dep.md
- config/src/node_key.rs
- p2p/Cargo.toml
- p2p/src/error.rs
- p2p/src/secret_connection.rs
- p2p/src/secret_connection/amino_types.rs
- p2p/src/secret_connection/protocol.rs
- p2p/src/secret_connection/public_key.rs
- pbt-gen/src/time.rs
- proto/src/serializers/timestamp.rs
- tendermint/Cargo.toml
- tendermint/src/account.rs
- tendermint/src/error.rs
- tendermint/src/private_key.rs
- tendermint/src/public_key.rs
- tendermint/src/signature.rs
- tendermint/src/time.rs
- tendermint/src/validator.rs
- test/Cargo.toml
- test/src/test/unit/p2p/secret_connection.rs
- testgen/Cargo.toml
- testgen/src/helpers.rs
- testgen/src/validator.rs
- testgen/src/vote.rs
> deps:  Use ed25519-consensus instead of ed25519-dalek

- .changelog/unreleased/dependencies/1068-remove-native-tls.md
- rpc/Cargo.toml
> rpc: Switch hyper-proxy to use rustls (backport to v0.23.x)

- .changelog/unreleased/dependencies/1068-remove-native-tls.md
- rpc/Cargo.toml
Fixes: https://github.com/informalsystems/ibc-rs/issues/1641
The rest of the stack already uses rustls for their TLS needs.
* ~Updated all code comments where relevant~
> rpc: Switch hyper-proxy to use rustls

- .changelog/v0.23.4/dependencies/1068-remove-native-tls.md
- .changelog/v0.23.4/summary.md
- CHANGELOG.md
- abci/Cargo.toml
- config/Cargo.toml
- light-client-js/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- light-client/src/lib.rs
- p2p/Cargo.toml
- p2p/src/lib.rs
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- proto/src/lib.rs
- rpc/Cargo.toml
- std-ext/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/lib.rs
- test/Cargo.toml
- testgen/Cargo.toml
- tools/abci-test/Cargo.toml
- tools/kvstore-test/Cargo.toml
- tools/kvstore-test/tests/light-client.rs
- tools/rpc-probe/Cargo.toml
Fixes merge conflicts in #1072 and harmonizes versioning with the `v0.23.x` branch (which has since been bumped to v0.23.4).
> light-client refactor: Merge latest changes from v0.23.x

- tools/rpc-probe/src/plan.rs
- tools/rpc-probe/src/quick.rs
Minor tweak to remove/use private fields in the rpc-probe's `PlanConfig` struct.
> Fix clippy warnings in rpc-probe

- light-client/src/supervisor.rs
- light-client/tests/backward.rs
- testgen/Cargo.toml
- testgen/src/commit.rs
- testgen/src/header.rs
- testgen/src/light_block.rs
- testgen/src/vote.rs
Fixes https://github.com/informalsystems/ibc-rs/issues/1687
The current tendermint-testgen header records time as `u64` in second precision. This means that any sub-second update will trim to the same second, causing the light client verification to fail if two headers fall in the same second. Using the proper `Time` struct will resolve this issue, allowing the header of a new block to have lower than a second difference than the previous block.
> Use Time instead of u64 seconds in tendermint-testgen Header (v0.23)

- light-client/src/supervisor.rs
- light-client/tests/backward.rs
- testgen/Cargo.toml
- testgen/src/commit.rs
- testgen/src/header.rs
- testgen/src/light_block.rs
- testgen/src/vote.rs
Same as #1080 targeted for `master` branch.
> Use Time instead of u64 seconds in tendermint-testgen Header (master)

- .changelog/unreleased/improvements/1077-private-key-clone.md
- tendermint/src/private_key.rs
> tendermint: Derive `Clone` for `tendermint::PrivateKey`

- .changelog/unreleased/breaking-changes/1084-rpc-probe-gaia.md
- tools/rpc-probe/Cargo.toml
- tools/rpc-probe/src/client.rs
- tools/rpc-probe/src/common.rs
- tools/rpc-probe/src/gaia.rs
- tools/rpc-probe/src/kvstore.rs
- tools/rpc-probe/src/main.rs
- tools/rpc-probe/src/quick.rs
Backport of just the RPC probe updates from #1061
> backport: rpc-probe updates from #1061

- .github/workflows/test.yml
Minor PR to update nightly Rust in CI.
> ci: Bump nightly Rust to 2022-01-11

- .changelog/unreleased/workarounds/1021-rpc-block_results.md
- rpc/src/request.rs
- tendermint/src/public_key.rs
- tendermint/src/validator.rs
Backports just the `block_results` RPC endpoint-related changes from #1061.
> backport: `block_results` RPC endpoint changes from #1061

- .changelog/unreleased/breaking-changes/1064-infallible-encode_vec.md
- abci/src/application/kvstore/main.rs
- proto/src/lib.rs
- proto/tests/unit.rs
- tendermint/src/block/header.rs
- tendermint/src/public_key.rs
- tendermint/src/validator.rs
- tendermint/src/vote/sign_vote.rs
> Make encode_vec() infallible

- .github/workflows/test.yml
> backport/ci: Bump grcov version to 0.8.7

- .changelog/unreleased/dependencies/1097-contracts-dep.md
- config/src/config.rs
- light-client/Cargo.toml
- light-client/src/components/scheduler.rs
- light-client/src/evidence.rs
- light-client/src/light_client.rs
- light-client/src/peer_list.rs
- light-client/src/state.rs
- p2p/src/error.rs
- rpc/src/abci/transaction.rs
- tendermint/src/evidence.rs
Updates to address clippy warnings/errors in Rust v1.59.0.
> Fix clippy warnings from Rust v1.59.0

- .changelog/unreleased/dependencies/1097-contracts-dep.md
- config/src/config.rs
- light-client/Cargo.toml
- light-client/src/components/scheduler.rs
- light-client/src/evidence.rs
- light-client/src/light_client.rs
- light-client/src/peer_list.rs
- light-client/src/state.rs
- p2p/src/error.rs
- tendermint/src/abci/transaction.rs
- tendermint/src/evidence.rs
> backport: Fix clippy warnings from Rust v1.59.0 (#1097)

- .changelog/unreleased/features/1105-chain-id-constants.md
- tendermint/src/chain/id.rs
In PeggyJv/ocular#18 we are trying to create a registry of "well-known" chain IDs. I proposed using `tendermint::chain::Id` for this, but to do so we'd need to have a const initializer support.
This commit changes the internal representation of `chain::Id` to `Cow<'static, str>`. This permits a `const fn` initializer, but avoids adding a lifetime to `chain::Id` itself.
It also adds `chain::Id::new` which is defined as a `const fn`, which can be used to define chain ID constants.
> Add support for `tendermint::chain::Id` constants

- .changelog/unreleased/improvements/1106-genesis-app-state.md
- rpc/src/client.rs
- rpc/src/client/bin/main.rs
- rpc/src/endpoint/genesis.rs
- rpc/tests/gaia_fixtures.rs
- rpc/tests/kvstore_fixtures.rs
- tendermint/src/genesis.rs
- tools/kvstore-test/Cargo.toml
- tools/kvstore-test/tests/tendermint.rs
Resolves: #1106 
This PR basically modifies the `genesis()` RPC function like so ->
```patch
-    async fn genesis(&self) -> Result<Genesis, Error> 
+    async fn genesis<AppState>(&self) -> Result<Genesis<AppState>, Error>
```
(Many thanks to @romac for writing the code 🙏)
> Generic `AppState` for `genesis()`

- README.md
The tendermint/spec repo is archived and directs people to the URL in this patch.
> Updated spec url

- .cargo/audit.toml
Add an explicit audit config to control its behaviour, also ignore
advisory for serde_cbor until resolved.
Signed-off-by: xla <self@xla.is>
~~* [ ] Wrote tests~~
~~* [ ] Added entry in `.changelog/`~~
> meta: Add audit config

- docs/architecture/adr-009-transport-agnostic-peer-abstraction.md
- p2p/Cargo.toml
- p2p/src/transport.rs
While it was well-intended the reality is that it's going to be
impractical and hinder potential adoption trying to not give in to the
sweet siren sounds of the async ecosystem. The author since has changed
their stance and adopted a conviction that well tuned and guard-railed
async can be workable and lead to maintainable solutions. This
change-set is in preparation of bringing in peer and supervisor
abstractions as described in the ADR.
Signed-off-by: xla <self@xla.is>
_Individual commits are significant please review accordingly._
~~* [ ] Wrote tests~~
> p2p: Rework transport to be async

- .github/workflows/test.yml
Follows from https://github.com/informalsystems/tendermint-rs/pull/995#issuecomment-1094168166
This updates our coverage check in CI to use https://github.com/taiki-e/cargo-llvm-cov and Rust stable.
> ci: Update CI coverage check to use llvm-cov

- tendermint/Cargo.toml
Release notes: https://github.com/RustCrypto/elliptic-curves/pull/548
> Bump `k256` to v0.11

- tendermint/Cargo.toml
- tendermint/src/account.rs
These crates are both based on `digest` v0.10, which is also the same version used by `k256` v0.11 (#1129).
Note that the `ripemd160` crate is now deprecated:
https://docs.rs/ripemd160/latest/ripemd160/
The `ripemd` crate is the replacement. It has the same maintainers (@RustCrypto), but now combines the former `ripemd160` and `ripemd320` crates into a single crate.
> Bump `sha2` to v0.10; replace `ripemd160` with `ripemd` v0.1

- .cargo/audit.toml
- .changelog/unreleased/dependencies/1133-replace-serde-cbor.md
- light-client/Cargo.toml
- light-client/src/errors.rs
- light-client/src/store/sled/utils.rs
> `light-client`: Replace `serde_cbor` with `serde_json`

- .cargo/audit.toml
Running `cargo audit` locally fails due to a breaking change in the configuration file format.
> Update cargo audit config file format to v0.17.0

- .changelog/unreleased/bug-fixes/1132-allow-omitted-fields-in-abci_info.md
- proto/src/prost/tendermint.abci.rs
- rpc/Cargo.toml
- tools/proto-compiler/src/constants.rs
Fixes: #1132
The fields of the tendermint-go struct equivalent to `abci::ResponseInfo` are annotated with `json:"omitempty"`, so give them default values for `Deserialize`. The `/abci_info` endpoint is known to omit the `app_version` field in some recent revisions of Gaia.
> Fix JSON deserialization of abci::ResponseInfo

- .changelog/unreleased/breaking-changes/1144-update-config-v0.35.md
- config/src/config.rs
- config/src/lib.rs
- config/src/serialization.rs
- config/tests/mod.rs
- config/tests/support/config/config.toml
> Update configuration file format for Tendermint v0.35

- .changelog/unreleased/features/1134-proto-grpc.md
- proto/Cargo.toml
- proto/src/lib.rs
- proto/src/prost/tendermint.abci.rs
- proto/src/prost/tendermint.privval.rs
- proto/src/prost/tendermint.rpc.grpc.rs
- tools/proto-compiler/Cargo.toml
- tools/proto-compiler/src/main.rs
- `proto-compiler` uses `tonic-build`
- tendermint-proto can be compiled with std for the `grpc` feature
(as required by the generated `tonic` code)
- the primary motivation is the new gRPC-based PrivVal interface
in Tendermint 0.35
(see https://github.com/informalsystems/tendermint-rs/issues/1134)
> tendermint-proto: Add a feature flag and generate gRPC server definitions

- .changelog/unreleased/breaking-changes/1140-sanitize-abci-slice-accessors.md
- rpc/src/abci/data.rs
- rpc/src/abci/log.rs
- rpc/tests/kvstore_fixtures.rs
It does not make sense to access wrapped data as references to container types `&Vec<u8>` and `&String`. Expose the data as slice references instead.
> rpc: Sanitize slice data accessors for ABCI types

- docs/architecture/adr-011-validator-crate.md
a proposed follow-up after
https://github.com/informalsystems/tendermint-rs/pull/1137
is merged.
ref: https://github.com/informalsystems/tendermint-rs/issues/1134
> ADR-011: Validator Crate

- .changelog/unreleased/dependencies/1153-k256-0.11.md
- p2p/Cargo.toml
- tendermint/Cargo.toml
and relaxed the crate version bounds
* [N/A] Updated all relevant documentation in docs
* [N/A] Updated all code comments where relevant
* [N/A] Wrote tests
> Update `k256` to v0.11 (fixes #1153) on v0.23.x

- rpc/src/client/transport/websocket.rs
- testgen/src/apalache.rs
Fixes some minor clippy lints.
> clippy: Fix lints for Rust 1.62 (v0.23.x)

- .changelog/unreleased/bug-fixes/1132-allow-omitted-fields-in-abci_info.md
- proto/src/prost/tendermint.abci.rs
- testgen/src/apalache.rs
- tools/proto-compiler/src/constants.rs
Backport of #1131 to v0.23.x
Should fix https://github.com/informalsystems/ibc-rs/issues/2444
The fields are annotated with `json:"omitempty"` in the Go source, so give them default values for `Deserialize`. The `/abci_info` endpoint is known to omit some of the fields depending on what the node software supplies.
> Fix JSON deserialization of abci::ResponseInfo (backport to v0.23.x)

- .changelog/unreleased/features/1169-basic-auth.md
- rpc/src/client/transport.rs
- rpc/src/client/transport/auth.rs
- rpc/src/client/transport/http.rs
- rpc/src/client/transport/websocket.rs
- rpc/src/rpc_url.rs
> v0.23.x: Add support for HTTP Basic authentication to HTTP and WebSocket RPC clients

- light-client/Cargo.toml
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- tendermint/Cargo.toml
- testgen/Cargo.toml
> Pin `time` to <0.3.12 to ensure we stay no-std compatible

- .changelog/unreleased/dependencies/1171-update-prost-0.11.md
- .github/workflows/build.yml
- abci/Cargo.toml
- p2p/Cargo.toml
- proto/Cargo.toml
- proto/src/prost/google.protobuf.rs
- proto/src/prost/tendermint.abci.rs
- proto/src/prost/tendermint.consensus.rs
- proto/src/prost/tendermint.privval.rs
- proto/src/prost/tendermint.rpc.grpc.rs
- proto/src/prost/tendermint.types.rs
- tendermint/Cargo.toml
- tools/proto-compiler/Cargo.toml
It appears as though this doesn't break anything. ~I've held back from regenerating the protos using this version of Prost due to this minor issue: https://github.com/tokio-rs/prost/issues/693~ This issue has now been fixed, so I've managed to regenerate the protos.
> Update Prost version to v0.11

- p2p/src/secret_connection/protocol.rs
> chore: Fix clippy warnings for Rust v1.64

- .changelog/unreleased/dependencies/1199-unpin-time-dep.md
- .github/workflows/test.yml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/time.rs
- testgen/Cargo.toml
It appears as though we no longer need the `time` dependency pinned for the no_std check to pass.
---
> deps: Unpin time dependency

- light-client-js/Cargo.toml
- light-client-js/src/lib.rs
Closes #1192.
`wee_alloc` was an optional dependency and an optimization anyways.
---
> deps: Remove `wee_alloc` optional dependency

- config/Cargo.toml
- tendermint/Cargo.toml
> deps: Remove `ansi_term` dependency

- .changelog/unreleased/bug-fixes/832-block-by-hash-encoding.md
- .changelog/unreleased/features/832-block-by-hash.md
- rpc/src/abci/tag.rs
- rpc/src/client.rs
- rpc/src/client/bin/main.rs
- rpc/src/endpoint.rs
- rpc/src/endpoint/block_by_hash.rs
- rpc/src/endpoint/tx.rs
- rpc/src/method.rs
- rpc/src/serializers.rs
- rpc/src/serializers/opt_tm_hash_base64.rs
- rpc/src/serializers/tm_hash_base64.rs
- rpc/src/serializers/tx_hash_base64.rs
- rpc/tests/kvstore_fixtures.rs
- rpc/tests/kvstore_fixtures/incoming/block_by_hash.json
- rpc/tests/kvstore_fixtures/outgoing/block_by_hash.json
- tools/kvstore-test/tests/tendermint.rs
- tools/rpc-probe/src/common.rs
- tools/rpc-probe/src/kvstore.rs
Links https://github.com/informalsystems/tendermint-rs/issues/832.
Re-implements the `block_by_hash` RPC, which returns an optional block.
I applied the patch from https://github.com/informalsystems/tendermint-rs/pull/1089 and fixed the `tendermint::Hash` encoding/decoding to accommodate discrepancies in how the Tendermint RPC encodes this field for different RPC interfaces.
Relates to #942 
CC @hansl
> Re-add `block_by_hash` Tendermint endpoint

- proto/src/serializers/optional.rs
With a bit less spiffy syntax, an `Option<T>` can be serialized without cloning the whole value.
> Serialization of optional values without Clone

- proto/src/serializers.rs
- proto/src/serializers/bytes.rs
- proto/src/serializers/nullable.rs
- proto/src/serializers/optional.rs
- proto/src/serializers/txs.rs
- tendermint/src/hash.rs
- tendermint/src/serializers/option_hash.rs
> docs: Fix unclosed HTML tags errors

- proto/src/serializers/bytes.rs
> docs: Apply suggestions from #1212 code review

- .changelog/unreleased/bug-fixes/1208-trustthresholdfraction-check.md
- tendermint/proptest-regressions/trust_threshold.txt
- tendermint/src/trust_threshold.rs
> `TrustThresholdFraction`: allow to be initialized with value 1

- light-client-verifier/src/operations/commit_validator.rs
- p2p/src/secret_connection.rs
- proto/tests/unit.rs
- tendermint/src/time.rs
- testgen/src/commit.rs
- testgen/src/tester.rs
> chore: Fix clippy lints for Rust 1.65

- .changelog/unreleased/improvements/1175-unix-timestamp-conversion.md
- tendermint/src/time.rs
close #1175 
I thought it would be easier to write code with other time libraries such as `chrono` if it porivided a `unix timestamp`
> Tendermint: Added `unix_timestamp` and `unix_timestamp_nanos` method in Time struct.

- .changelog/unreleased/improvements/1230-query-api.md
- rpc/src/query.rs
> tendermint-rpc: Improve `Query` API

- .changelog/unreleased/breaking-changes/1095-abci-change-bytes-to-hash.md
- rpc/tests/kvstore_fixtures.rs
- tendermint/src/abci/request/offer_snapshot.rs
- tendermint/src/abci/response/info.rs
- tendermint/src/abci/response/init_chain.rs
- tendermint/src/genesis.rs
- tendermint/src/hash.rs
Fixes: #1095
Both questions in https://github.com/informalsystems/tendermint-rs/issues/1095#issuecomment-1279223745 are resolved with "Yes".
> abci: Change hashes' type from `Bytes` to `tendermint::Hash` or `tendermint::AppHash`

- .changelog/unreleased/breaking-changes/1234-decouple-rpc-from-proto.md
- .changelog/unreleased/improvements/1234-decouple-rpc-from-proto.md
- rpc/Cargo.toml
- rpc/src/endpoint/abci_query.rs
- rpc/src/endpoint/block_search.rs
- rpc/src/endpoint/tx.rs
- rpc/src/endpoint/tx_search.rs
- rpc/src/endpoint/validators.rs
- rpc/src/event.rs
- rpc/src/query.rs
- rpc/src/serializers.rs
- rpc/tests/kvstore_fixtures.rs
- tendermint/src/abci/response/query.rs
- tendermint/src/error.rs
- tendermint/src/lib.rs
- tendermint/src/merkle.rs
- tendermint/src/merkle/proof.rs
- tendermint/src/tx.rs
- tendermint/src/tx/proof.rs
Fixes: #1233
Replace remaining use of `prost-build`-generated structs in `tendermint-rpc` with domain types newly defined in `tendermint`.
In `tendermint`, `merkle::proof::Proof` was named inconsistently with regard to protobuf, which has it as `crypto.ProofOps`, yet also the `crypto.Proof` message is defined, which we make use of now. Renamed that domain type to `ProofOps` to make way for the newly added `Proof`.
> Decouple tendermint-rpc from tendermint-proto

- tendermint/Cargo.toml
The macro is not used anywhere by tendermint,
let's speed up compile times by removing it from the build.
> Remove async-trait from dependencies

- .changelog/unreleased/improvements/1242-serde-wasm-bindgen.md
- light-client-js/Cargo.toml
- light-client-js/src/lib.rs
- light-client-js/tests/web.rs
- proto/src/serializers/part_set_header_total.rs
The bug this used to work around is closed and the problem
no longer seems to persist.
> light-client-js: remove the syn version pin

- .changelog/v0.28.0/breaking/0000-light-client-verification-preds.md
- .changelog/v0.28.0/breaking/0000-light-client-verifier.md
- .changelog/v0.28.0/security/0000-light-client-security.md
- CHANGELOG.md
Removes the incorrect PR references from the v0.28.0 changelog.
> Fix changelog for v0.28.0 release

- .changelog/unreleased/bug-fixes/1246-verify-between-trusted.md
- .github/workflows/test.yml
- light-client/src/components/scheduler.rs
- light-client/src/light_client.rs
- light-client/src/store.rs
- light-client/src/store/memory.rs
- light-client/src/store/sled.rs
- light-client/src/store/sled/utils.rs
- light-client/src/supervisor.rs
- light-client/src/tests.rs
> light-client: Fix verification of blocks between two trusted heights

- tendermint/Cargo.toml
The `tendermint` crate uses features of `bytes` introduced in version 1.2, namely a `From<Vec<u8>>` impl for `Bytes`.
See https://github.com/cosmos/cosmos-rust/pull/314 for additional context
> tendermint: fix minimal-versions correctness for `bytes`

- .changelog/unreleased/dependencies/1046-ed25519-consensus-dep.md
- config/src/node_key.rs
- p2p/Cargo.toml
- p2p/src/error.rs
- p2p/src/secret_connection.rs
- p2p/src/secret_connection/amino_types.rs
- p2p/src/secret_connection/protocol.rs
- p2p/src/secret_connection/public_key.rs
- tendermint/Cargo.toml
- tendermint/src/account.rs
- tendermint/src/error.rs
- tendermint/src/private_key.rs
- tendermint/src/public_key.rs
- tendermint/src/signature.rs
- tendermint/src/validator.rs
- test/Cargo.toml
- test/src/test/unit/p2p/secret_connection.rs
- testgen/Cargo.toml
- testgen/src/helpers.rs
- testgen/src/validator.rs
- testgen/src/vote.rs
Backports this change to the new `main` (was #1067).
* Use ed25519-consensus instead of ed25519-dalek
Closes #355 (see that issue for more context; `ed25519-consensus` is a fork of `ed25519-zebra` that's Zcash-independent).
This change ensures that `tendermint-rs` has the same signature verification as `tendermint`, which uses the validation criteria provided by the Go `ed25519consensus` library.
* clippy fixes
Co-authored-by: Thane Thomson <connect@thanethomson.com>
* Remove redundant dependency
Signed-off-by: Thane Thomson <connect@thanethomson.com>
* cargo fmt
Signed-off-by: Thane Thomson <connect@thanethomson.com>
* Add changelog entries
Signed-off-by: Thane Thomson <connect@thanethomson.com>
Co-authored-by: Henry de Valence <hdevalence@penumbra.zone>
> deps:  Use ed25519-consensus instead of ed25519-dalek (#1067)

- light-client-verifier/src/operations/commit_validator.rs
- light-client-verifier/src/verifier.rs
Hermes needs `PartialEq` and `Eq` implemented on `ProdVerifier`. No idea why, but it's simple to add the derives
rather than fighting this downstream.
Also add test code that ensures `ProdVerifier` supports the common derived traits.
> Derive PartialEq, Eq on ProdCommitValidator

- .github/workflows/release.yml
- release.sh
Relates to #707.
This simply allows us to execute the `release.sh` script by way of pushing tags to the repository. In future we may want to consider using a more sophisticated, robust process, but for now this should work.
Allows for the publishing of crates on behalf of @bftbot.
> ci: Automate release process

- .github/workflows/release.yml
I incorrectly set the runner for the release workflow to `ubuntu` instead of `ubuntu-latest` in #1268, so GitHub wouldn't pick it up.
> ci: Fix runner for release workflow

- tools/proto-compiler/Cargo.toml
Fixes:
https://github.com/informalsystems/tendermint-rs/security/dependabot/2
> Update git2 dependency to 0.16

- .changelog/unreleased/breaking-changes/1276-tungstenite-0.18.md
- rpc/Cargo.toml
Dependency bump. No changes needed in the code, but since we
re-export `WebSocketConfig` from tungstenite in the tendermint-rpc API, this is still a breaking change.
> Bump async-tungstenite dependency to 0.20

- .changelog/unreleased/improvements/1278-re-add-hash-on-time.md
- tendermint/src/time.rs
This reintroduces #1054 after it was removed in #1203.
I believe there was no concern in having `Time` derive `Hash` so it seems fine to re-apply this change.
> Derive `Hash` on `tendermint::Time` again

- .changelog/unreleased/improvements/1280-max-drift-error.md
- light-client-verifier/src/errors.rs
- light-client-verifier/src/predicates.rs
> Show `max_clock_drift` in error raised when header is from the future

- CONTRIBUTING.md
As there is now the release workflow triggered on release tags,
update the release process instructions to take account of it.
> Update CONTRIBUTING to release workflow in CI

- light-client-verifier/src/verifier.rs
As this is a trivial PR, I didn't create a new issue.
I just wanted to make this clarification directly in tendermint-rs, as we forgot to make that check in ibc-rs (https://github.com/cosmos/ibc-rs/issues/583).
> tendermint-light-client: add clarifying comment

- .changelog/unreleased/breaking-changes/1290-signature-v2.md
- .github/workflows/rust.yml
- Cargo.toml
- p2p/Cargo.toml
- tendermint/Cargo.toml
- tendermint/src/account.rs
- tendermint/src/crypto/default/signature.rs
- tendermint/src/public_key.rs
- tendermint/src/signature.rs
- tendermint/src/test.rs
- tendermint/src/vote.rs
- tendermint/tests/alt_crypto.rs
Closes: #1290
Bumps all of the above dependencies to their latest versions, which use the new `signature` v2 release:
https://github.com/RustCrypto/traits/pull/1211
> Bump `ed25519` => v2; `k256` => v0.13; `signature` => v2

- .changelog/unreleased/improvements/1293-buf-proto-deps.md
- .github/workflows/build.yml
- proto/src/prost/v0_34/tendermint.abci.rs
- proto/src/prost/v0_34/tendermint.crypto.rs
- proto/src/prost/v0_34/tendermint.privval.rs
- proto/src/prost/v0_34/tendermint.types.rs
- proto/src/prost/v0_37/tendermint.abci.rs
- proto/src/prost/v0_37/tendermint.crypto.rs
- proto/src/prost/v0_37/tendermint.privval.rs
- proto/src/prost/v0_37/tendermint.types.rs
- proto/src/tendermint/v0_34.rs
- proto/src/tendermint/v0_37.rs
- tools/proto-compiler/Cargo.toml
- tools/proto-compiler/src/buf_build.rs
- tools/proto-compiler/src/constants.rs
- tools/proto-compiler/src/functions.rs
- tools/proto-compiler/src/main.rs
> Parse and fetch proto dependencies from `buf.lock` in the repository source

- .changelog/unreleased/improvements/1288-typedevent-trait.md
- tendermint/src/abci/event.rs
Downstream users of ABCI need to encode data in ABCI `Event`s.  Different consumers of these events may have different requirements on the event structure.  For instance, the Go IBC relayer expects to see an event with a hex-encoded representation of a client state.
To ensure that there's a single source of truth for these kinds of encodings, it would be useful for downstream users of the `abci::Event` type to be able to write custom domain types for particular event types.  This PR adds an `abci::TypedEvent` trait that captures the conversion relationships between an `Event` and a domain type.  It also defines a contract about how the conversion between raw events and domain types should handle index information, which is nondeterministic: if `T: TypedEvent`, then:
- `T::try_from(e) == …
> Add a `TypedEvent` conversion trait for ABCI events.

- .changelog/unreleased/breaking-changes/1290-signature-v2.md
- .changelog/unreleased/improvements/1288-typedevent-trait.md
- .changelog/unreleased/improvements/1293-buf-proto-deps.md
- CHANGELOG.md
- abci/Cargo.toml
- config/Cargo.toml
- light-client-js/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- p2p/Cargo.toml
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- rpc/Cargo.toml
- std-ext/Cargo.toml
- tendermint/Cargo.toml
- test/Cargo.toml
- testgen/Cargo.toml
- tools/abci-test/Cargo.toml
- tools/kvstore-test/Cargo.toml
- tools/rpc-probe/Cargo.toml
Prepares an `v0.31.0` release.  This is technically a breaking change because of the signature upgrades, but should otherwise be a trivial upgrade.
> Prepare v0.31.0 release

- .changelog/unreleased/features/1288-typed_events.md
- tendermint/src/abci.rs
This is a trivial API changes that exposes the `tendermint::abci::event::TypedEvent` marker trait.
> Expose the `TypedEvent` conversion trait

- .changelog/unreleased/breaking-changes/1294-verify-update-header.md
- .changelog/unreleased/features/1294-verify-misbehavior-header.md
- light-client-js/src/lib.rs
- light-client-verifier/src/verifier.rs
- light-client/src/light_client.rs
- light-client/src/tests.rs
> Add `Verifier::verify_misbehaviour_header` for verifying headers coming from a misbehaviour evidence

- .rustfmt.toml
These options cannot be used on stable Rust, which we use for developing the library and on CI for checking the formatting. As such they should be removed from the `.rustfmt.toml` config, as they can otherwise be picked up by some IDEs which will automatically use the nightly `rustfmt` to honor the unstable options.
> Remove nightly-only options in rustfmt config

- .changelog/unreleased/improvements/1310-loosen-merkle-tree-bounds.md
- tendermint/src/merkle.rs
Closes #1310 
* [] Wrote tests (N/A)
> Loosen bounds on merkle hash arguments

- light-client-cli/README.md
- release.sh
> Fix release script when a crate is not yet published at all on crates.io

- .changelog/unreleased/breaking-changes/1321-status-earliest-block.md
- rpc/src/endpoint/status.rs
- rpc/tests/kvstore_fixtures/v0_34.rs
- rpc/tests/kvstore_fixtures/v0_37.rs
This is a trivial addition of missing /status RPC fields, specifically the "earliest block" information.
This information is useful and tells us the range of blocks that can be queried from a node. To be used for a Cosmos block crawler/indexer project.
I deemed the change so minor as to not warrant a changelog entry.
> RPC: Provide earliest block information from /status

- proto/src/serializers/from_str.rs
- rpc/src/response.rs
This fixes the `from_str` serialization. I discovered this while trying to serialize and deserialize the response type for `broadcast_tx_commit` while making a mock tendermint server; the `gas_wanted` field and a few others were serialized as integers, but were decoded as a string, causing an error `invalid type: integer `0`, expected a string at line 1 column 98`. `Display` formats the integer without quotes, but we wanted with quotes.
Before:
```
"{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{\"check_tx\":{\"code\":0,\"data\":[],\"log\":\"\",\"info\":\"\",\"gas_wanted\":0,\"gas_used\":0,\"events\":[],\"codespace\":\"\",\"sender\":\"\",\"priority\":0,\"mempool_error\":\"\"},\"deliver_tx\":{\"code\":0,\"data\":[],\"log\":\"\",\"info\":\"\",\"gas_wanted\":0,\"gas_used\":0,\"events\":[],\"codesp …
```
> fix `from_str` serializer

- .changelog/unreleased/bug-fixes/1326-compat-for-latest_block_results.md
- rpc/src/client/transport/http.rs
- rpc/src/client/transport/websocket.rs
Fixes: #1325 as it applies to the implementations of `Client::latest_block_results`
> rpc: use compat mode in latest_block_results()

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/no-std.yaml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/test.yml
- tendermint/src/hash.rs
Update GitHub workflows to use up-to-date actions:
- Bump actions/checkout to v3
- Replace actions-rs/toolchain with dtolnay/rust-toolchain
- Replace actions-rs/audit-check with rustsec/audit-check
- Replace actions-rs/clippy-check with giraffate/clippy-action
- Update protoc, buf, and grcov to latest versions.
> Update GitHub actions

- rpc/tests/osmosis_fixtures.rs
- rpc/tests/osmosis_fixtures/incoming/block_results_at_height_10499831.json
While investigating #1325 I've extracted some response content from Osmosis
to test against. This should not go to waste, as the response features some
fields with non-trivial values not seen in other fixtures, e.g. `txs_results`.
> rpc: add test against fixture from Osmosis

- .changelog/v0.32.2/summary.md
- CHANGELOG.md
- abci/Cargo.toml
- config/Cargo.toml
- light-client-cli/Cargo.toml
- light-client-cli/README.md
- light-client-detector/Cargo.toml
- light-client-js/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- p2p/Cargo.toml
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- rpc/Cargo.toml
- std-ext/Cargo.toml
- tendermint/Cargo.toml
- test/Cargo.toml
- testgen/Cargo.toml
- tools/abci-test/Cargo.toml
- tools/kvstore-test/Cargo.toml
- tools/rpc-probe/Cargo.toml
Fixes a minor metadata problem that was one of the blockers for releasing all crates of 0.32.1.
> Release 0.32.2

- .changelog/v0.32.2/summary.md
- CHANGELOG.md
- abci/Cargo.toml
- config/Cargo.toml
- light-client-cli/Cargo.toml
- light-client-detector/Cargo.toml
- light-client-js/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- p2p/Cargo.toml
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- rpc/Cargo.toml
- std-ext/Cargo.toml
- tendermint/Cargo.toml
- test/Cargo.toml
- testgen/Cargo.toml
- tools/abci-test/Cargo.toml
- tools/kvstore-test/Cargo.toml
- tools/rpc-probe/Cargo.toml
Changelog and cargo file changes from release 0.32.2.
The README for `tendermint-light-client-cli` is already better in main,
so the content released in 0.32.2 was omitted.
> Merge v0.32.2

- .changelog/unreleased/breaking-changes/1323-encode-vec-no-error.md
- proto/src/lib.rs
- proto/tests/unit.rs
- tendermint/src/block/header.rs
- tendermint/src/proposal.rs
- tendermint/src/proposal/sign_proposal.rs
- tendermint/src/public_key.rs
- tendermint/src/public_key/pub_key_request.rs
- tendermint/src/validator.rs
- tendermint/src/vote.rs
- tendermint/src/vote/sign_vote.rs
> imp(Protobuf)!: align`encode{,_length_delimited}_vec` with `prost::Message` to return `Vec<u8>`

- CHANGELOG.md
- abci/Cargo.toml
- config/Cargo.toml
- light-client-cli/Cargo.toml
- light-client-detector/Cargo.toml
- light-client-js/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- p2p/Cargo.toml
- p2p/src/secret_connection.rs
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- rpc/Cargo.toml
- std-ext/Cargo.toml
- tendermint/Cargo.toml
- test/Cargo.toml
- testgen/Cargo.toml
- tools/abci-test/Cargo.toml
- tools/kvstore-test/Cargo.toml
- tools/rpc-probe/Cargo.toml
> release: prepare `v0.33.1`

- .changelog/unreleased/breaking-changes/1351-serializer-fixes.md
- .changelog/unreleased/improvements/1351-serializer-improvements.md
- proto/src/serializers/from_str.rs
- proto/src/serializers/nullable.rs
- proto/src/serializers/optional.rs
- proto/src/serializers/optional_from_str.rs
- tendermint/src/serializers/apphash.rs
- tendermint/src/serializers/apphash_base64.rs
- tendermint/src/serializers/hash.rs
- tendermint/src/serializers/option_hash.rs
The custom field serializers in `tendermint` and `tendermint-proto` have a few problems.
The modules where the deserializers expect the values to be an `Option` (i.e. nullable) do not consistently use `Serializer::serialize_some` when serializing a non-null value. This is not an issue with `serde_json`, but as the serde framework is generic, this implementation will break with other serializers, particularly for non-self-describing formats.
Deserializer functions unconditionally allocate temporary strings where they can potentially be borrowed from the deserializer, achieving zero copies from source data.
These changes correct the serde schema issues and introduce optimization by deserializing strings into `Cow`, allowing use of borrowed string values from deserializers that support it.
> Correct and optimize custom serializers for stringized values, hashes, nullable and optional fields

- .changelog/unreleased/bug-fixes/1348-valset-deserialization-fixes.md
- .changelog/unreleased/bug-fixes/1350-pubkey-serde-fixes.md
- .changelog/unreleased/improvements/1348-valset-deserialization-fixes.md
- proto/src/prost/v0_34/tendermint.crypto.rs
- proto/src/prost/v0_34/tendermint.types.rs
- proto/src/prost/v0_37/tendermint.crypto.rs
- proto/src/prost/v0_37/tendermint.types.rs
- proto/src/prost/v0_38/tendermint.crypto.rs
- proto/src/prost/v0_38/tendermint.types.rs
- proto/src/serializers.rs
- proto/src/serializers/from_str_allow_null.rs
- proto/src/serializers/public_key.rs
- tendermint/src/error.rs
- tendermint/src/validator.rs
- tools/proto-compiler/src/constants.rs
Closes #1348
Use the validating conversion from the protobuf struct `ValidatorSet`, which has the same schema including the now optionally deserialized `total_voting_power` field.
This is to ensure we don't blindly trust `total_voting_power` if it's
present in the serialization, and accept when it's absent.
Also ensure no integer overflows can occur while calculating the total voting power, and check the resulting power against
the protocol-defined sanity limit.
> Validate construction and deserialization of `validator::Set`

- .changelog/unreleased/bug-fixes/1352-fix-absent-vote-json.md
- tendermint/src/block/commit_sig.rs
See #1352 for the rationale behind this fix.
> Fix JSON serialization of `timestamp` field for `CommitSig::BlockIdFlagAbsent`

- .changelog/unreleased/improvements/1343-add-app-hash-field-to-testgen-header.md
- p2p/src/secret_connection.rs
- tendermint/src/hash.rs
- testgen/src/header.rs
- testgen/src/light_block.rs
Closes: #1343
Use case: https://github.com/informalsystems/hermes/pull/3566
> tendermint-testgen: Add `app_hash` field to `Header`

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/no-std.yaml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/test.yml
Fix a breakage in the cargo doc check.
Also update to `actions/checkout@v4`.
> CI: doc build fix, update actions/checkout

- .changelog/unreleased/improvements/1359-hande-http-error.md
- rpc/Cargo.toml
- rpc/src/client/transport/http.rs
- rpc/src/error.rs
Closes: #1359
This PR checks for the status code to be 200 OK, if not it returns an error with the actual status code and the body of the response, but does not attempt to parse the response body as a JSON-RPC payload.
CometBFT will [always set the status code](https://github.com/cometbft/cometbft/blob/86c07f20f163c17a0f5b7149cbd441a242b88557/rpc/jsonrpc/server/http_server.go#L151) to 200 OK and the content type to JSON for response which were successfully handled (which does mean that the JSON-RPC response itself is successful).
> Turn non-200 HTTP responses into an error instead of trying to parse the body as a JSON-RPC response

- Cargo.toml
Fix the following cargo warning when building the workspace:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
> Fix cargo warning by explicitly specifying a resolver for the workspace

- .changelog/unreleased/breaking-changes/1365-cometbft-0.38.0.md
- proto/src/prost/v0_38/tendermint.abci.rs
- proto/src/tendermint/v0_38.rs
- tendermint/src/abci/request/extend_vote.rs
- tools/proto-compiler/src/constants.rs
Since v0.38.0-rc3, there were quite a few fields added to the
`RequestExtendVote` message.
Represent them in the domain type for the request.
> Update to CometBFT 0.38.0 release

- p2p/Cargo.toml
- p2p/src/secret_connection.rs
- p2p/src/secret_connection/protocol.rs
- test/Cargo.toml
- test/src/test/unit/p2p/secret_connection.rs
The `tendermint-p2p` crate previously pulled in both an obsolete version of `x25519-dalek`/`curve25519-dalek`, but also `curve25519-dalek-ng` by way of `ed25519-consensus`.
This replaces `x25519-dalek` with `curve25519-dalek-ng` which is already a dependency of `ed25519-consensus`. This reduces the overall number of dependencies and ensures `curve25519-dalek-ng` is the main Curve25519 implementation used.
Note: I don't have an open issue for this but since it reduces the overall number of dependencies I thought it made sense.
> p2p: replace `x25519-dalek` with `curve25519-dalek-ng`

- p2p/Cargo.toml
- p2p/src/secret_connection.rs
Updates to the latest version of the `chacha20poly1305` crate
> p2p: bump `chacha20poly1305` to v0.10

- .changelog/unreleased/breaking-changes/eyre_tracer.md
- abci/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- tendermint/Cargo.toml
- tools/abci-test/Cargo.toml
Don’t enable flex-error/eyre_tracer feature in crates which don’t use
eyre directly.  This allows customers depend on say tendermint crate
without having to pull in eyre crate.  This is useful because eyre
uses mutable static variables (specifically HOOK variable) which is
incompatible with some blockchain runtimes.
* [n/a] Referenced an issue explaining the need for the change
* [n/a] Wrote tests
> Avoid enabling flex-error/eyre_tracer feature

- .github/workflows/test.yml
- config/src/prelude.rs
- light-client-verifier/src/prelude.rs
- proto/src/prelude.rs
Fix the `nightly-coverage` CI job by adjusting the flag for the nightly
rustc compiler.
Also throw in `-C link-dead-code` into the compiler flags for the
nightly-coverage CI job.
> Update rustc option for instrument-coverage

- .changelog/unreleased/breaking-changes/1375-allow-null-in-event-attributes.md
- tendermint/src/abci/event.rs
Fixes #1375
When deserializing `EventAttribute` values, allow null values in the key and value fields. This follows the behaviour in 0.34 RPC (where the key-value data were also base64-encoded), but technically breaks the serde schema of everything that includes ABCI event data.
> tendermint: allow null in `EventAttribute` kv JSON

- .changelog/unreleased/improvements/1378-expose-rpc-client-builders.md
- rpc/src/client.rs
Re-export `client::transport::{http, websocket}` (guarded by appropriate feature gates) publicly under the `client` module.
This exposes the `Builder` types defined in each of the modules as public API, with properly built documentation.
> rpc: expose `http::Builder`, `websocket::Builder` under `client`

- .changelog/unreleased/breaking-changes/1382-add-codespace-error.md
- rpc/src/endpoint/broadcast/tx_async.rs
- rpc/src/endpoint/broadcast/tx_sync.rs
Closes: #1382
This PR adds the `codespace` field to Tx sync and async `Response` which gives additional information on the source of the error.
> Add `codespace` field to Tx sync and async `Response`

- CHANGELOG.md
- rpc/src/client.rs
- rpc/src/client/subscription.rs
Closes: https://github.com/informalsystems/tendermint-rs/issues/1385
> rpc: Make `rpc::Client` and `SubscriptionClient` traits `?Send` under `wasm32` target

- abci/Cargo.toml
- config/Cargo.toml
- light-client-detector/Cargo.toml
- light-client-js/Cargo.toml
- light-client/Cargo.toml
- light-client/tests/backward.rs
- light-client/tests/model_based.rs
- p2p/Cargo.toml
- p2p/src/lib.rs
- proto/Cargo.toml
- rpc/Cargo.toml
- rpc/src/utils.rs
- rpc/tests/kvstore_fixtures/v0_34.rs
- rpc/tests/kvstore_fixtures/v0_37.rs
- rpc/tests/kvstore_fixtures/v0_38.rs
- tendermint/src/chain/id.rs
- tendermint/src/crypto/ed25519/signing_key.rs
- tendermint/src/error.rs
- test/Cargo.toml
- testgen/Cargo.toml
- testgen/src/tester.rs
> Update dependencies and fix new warnings

- .changelog/unreleased/bug-fixes/1393-p2p-data-corruption.md
- p2p/src/secret_connection.rs
- test/src/test/unit/p2p/secret_connection.rs
The code handling chunking of data frames longer than the configured
maximum was faulty.
May fix #1392 and possibly other occurrences of data corruption.
> p2p: fix data corruption on longer packets

- .changelog/unreleased/improvements/1379-rpc-http-timeout.md
- rpc/src/client/transport/http.rs
Simply introduces a HTTP timeout parameter, which is passed to reqwest.
This is highly desirable a the default behaviour is "no timeout", which can result in stalls.
Closes #1379.
> rpc: Add HTTP timeout, default 30 seconds.

- .changelog/unreleased/bug-fixes/1391-block-results-not-ok.md
- rpc/src/dialect/deliver_tx.rs
- rpc/tests/sei_fixtures.rs
- rpc/tests/sei_fixtures/incoming/block_results_with_failed_txs.json
- tendermint/src/abci/types.rs
See https://github.com/informalsystems/hermes/issues/3817#issuecomment-1916478908 for background.
---
> rpc: Fix deserialization of `/block_results` response when some tx results are non-ok

- .changelog/unreleased/features/1401-ed25519-consensus-from-impls.md
- tendermint/src/crypto/ed25519/signing_key.rs
- tendermint/src/crypto/ed25519/verification_key.rs
- tendermint/src/private_key.rs
- tendermint/src/public_key.rs
currently, when working with `tendermint::{PrivateKey, PublicKey}`, users of the `ed25519-consensus` crate must convert a `ed25519_consensus::VerificationKey` or `ed25519_consensus::SigningKey` via `TryFrom<&'_ [u8]>`. this has the unfortunate effect of requiring a bounds check, on a value that is already known to be a valid key.
```rust
tendermint::PublicKey::from_raw_ed25519(&vk.to_bytes()).expect("consensus key is valid")
```
this branch introduces some additional `From<T>` implementations, to facilitate free conversions from `ed25519-consensus` types.
* 649dd37e tendermint: `PrivateKey` is `From<ed25519_consensus::SigningKey>`
* 4f1a95a4 tendermint: `SigningKey` is `From<ed25519_consensus::SigningKey>`
* ad24ea54 tendermint: `PublicKey` is `From<ed25519_consensus::VerificationKey>`
* …
> 🔁 `PrivateKey` and `PublicKey` have `From` impls for `ed25519-consensus` types

- .changelog/unreleased/improvements/1403-decode-empty-commit-in-block.md
- tendermint/src/block.rs
> tendermint: Allow misformed blocks when decoding them from Protobuf or RPC responses

- .changelog/unreleased/improvements/1406-optimise-voting_power_in.md
- light-client-verifier/src/operations/voting_power.rs
Rather than performing a linear search for a validator by its address, construct an index for the validator set sorted by address.  While building the index takes O(N log N) time, it cuts lookup to O(log n).
On Solana, with ~50 validators, this change causes reduction of the cost of a single lookup from 20k compute units to 700.
Furthermore, merge the index with the seen_validators map so that only a single lookup is now performed which allows us to find the validator and check whether it’s not a duplicate.
Closes: https://github.com/informalsystems/tendermint-rs/issues/1406
> light-client-verifier: optimise validator lookup in voting_power_in

- .changelog/unreleased/improvements/1411-validator-index-i32-max-limit.md
- tendermint/src/vote/validator_index.rs
During conversion from usize to ValidatorIndex first convert the value to `i32` to make sure that the value is ≤ i32::MAX.  Without that intermediate conversion, `u32::MAX as usize` is successfully converted into the index.
> tendermint: ensure ValidatorIndex is ≤ i32::MAX

- proto/src/lib.rs
example: https://github.com/informalsystems/tendermint-rs/actions/runs/9181862633/job/25249544213?pr=1423
```
error: unexpected `cfg` condition value: `grpc-client`
--> proto/src/lib.rs:3:46
|
3 | #![cfg_attr(not(any(feature = "grpc-server", feature = "grpc-client")), no_std)]
|                                              ^^^^^^^^^^^^^^^^^^^^^^^
|
= note: expected values for `feature` are: `default`, `grpc`, `grpc-server`, `tonic`
= help: consider adding `grpc-client` as a feature in `Cargo.toml`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
```
i noticed this error in ci for #1423, and #1422.
> ci: 🦀 fix nightly `cargo test-all-features`

- CHANGELOG.md
- proto/Cargo.toml
this upgrades tonic from `0.10` to `0.11`. no more, no less!
> proto: 🧪 upgrade to tonic 0.11

- .changelog/unreleased/breaking-changes/1423-verify-commit-restore.md
- CHANGELOG.md
- light-client-verifier/src/verifier.rs
in #1410, alterations were made to the `PredicateVerifier<P, C, V>` to improve performance when verifying commits.
specifically, a call to
`verify_commit_against_trusted(untrusted, trusted, options)` will now make use of new internal interfaces that check validator signatures and signer overlap at the same time.
this is a worthwhile performance improvement, but in the process, it made changes to the public interface of `PredicateVerifier<P, C, V>` that breaks some use cases. as i understand it, there is no strict need to remove the other public interface from the verifier. those that call `verify_commit_against_trusted` can still receive a performance boost, but calling `verify_commit` on just the untrusted state should still work after those changes.
so, this commit restores …
> light-client-verifier: 🌱 restore `verify_commit()` interface

- .changelog/unreleased/improvements/1425-add-http-client-user-agent.md
- rpc/src/client/transport/http.rs
Fixes https://github.com/informalsystems/tendermint-rs/issues/1425.
Need this to be able to specify a custom User-Agent for Hermes requests.
I am unsure how to test it properly with Hermes though; if someone can give me any hint on how to compile Hermes with this version of tendermint-rpc, I'd appreciate that.
> feat: add a way to provide a custom User-Agent

- .changelog/unreleased/features/1421-reqwest-client.md
- rpc/src/client/transport/http.rs
Previously, the reqwest client for HttpClient would be unconditionally built by the internal builder, meaning that useful middleware such as tower could not be applied.
This commits adds two ways to create the HttpClient with a custom reqwest::Client, either through new_from_parts, or using the builder.
> feat(rpc): expose reqwest client

- .changelog/unreleased/bug-fixes/1415-fix-optional-event-type.md
- rpc/Cargo.toml
- rpc/tests/dydx_fixtures.rs
- rpc/tests/dydx_fixtures/incoming/block_results_at_height_12791634.json
- tendermint/src/abci/event.rs
Fixes https://github.com/informalsystems/tendermint-rs/issues/1415
> fix(abci): Add serde `default` for `Event::type`

- .changelog/unreleased/improvements/1428-finalizeblock-deserialization.md
- tendermint/src/abci/response/finalize_block.rs
> fix(tendermint): Make `FinalizeBlock::validator_updates` nullable when deserializing

- .changelog/unreleased/breaking-changes/1435-block-domain-type.md
- tendermint/src/block.rs
Fix #1435, by removing extra-validation done on the `Block` domain type.
> tendermint:  relax `Block` validation rules to avoid assumptions on initial height

- .changelog/unreleased/features/1438-genesis-chunked-endpoint.md
- rpc/src/client.rs
- rpc/src/client/bin/main.rs
- rpc/src/endpoint.rs
- rpc/src/endpoint/genesis_chunked.rs
- rpc/src/method.rs
> rpc: Add `/genesis_chunked` query

- .changelog/unreleased/breaking-changes/1446-fix-prost-version.md
- tendermint/Cargo.toml
> fix: Bump `prost` and `prost-types` to latest versions in `tendermint` crate

- .changelog/unreleased/improvements/1449-allow-base64-apphash.md
- tendermint/src/hash.rs
- tendermint/src/serializers/apphash.rs
> rpc: Fix `AppHash` decoding failure in `/block_results` response

- .changelog/unreleased/bug-fixes/1457-remove-prost-types-dep.md
- proto/Cargo.toml
- tendermint/Cargo.toml
Now that #1452 has landed `prost-types` isn't used.
This removes it as a dependency.
> proto: remove `prost-types` dependency

- .changelog/unreleased/breaking-changes/1467-v038-dialect.md
- .changelog/unreleased/bug-fixes/1467-v038-evidence.md
- proto/src/prost/v0_34/tendermint.abci.rs
- proto/src/prost/v0_37/tendermint.abci.rs
- proto/src/prost/v0_38/tendermint.abci.rs
- proto/src/prost/v0_38/tendermint.types.rs
- proto/src/tendermint/v0_34.rs
- proto/src/tendermint/v0_37.rs
- proto/src/tendermint/v0_38.rs
- rpc/src/client/compat.rs
- rpc/src/client/transport.rs
- rpc/src/client/transport/http.rs
- rpc/src/client/transport/mock.rs
- rpc/src/client/transport/websocket.rs
- rpc/src/dialect.rs
- rpc/src/dialect/v0_38.rs
- rpc/src/endpoint/block.rs
- rpc/src/endpoint/block_by_hash.rs
- rpc/src/endpoint/block_results.rs
- rpc/src/endpoint/block_search.rs
- rpc/src/endpoint/broadcast/tx_commit.rs
- rpc/src/endpoint/header.rs
- rpc/src/endpoint/header_by_hash.rs
- rpc/src/endpoint/tx.rs
- rpc/src/endpoint/tx_search.rs
- rpc/tests/kvstore_fixtures/v0_37/incoming/block_search_evidence.json
- rpc/tests/kvstore_fixtures/v0_38.rs
- rpc/tests/kvstore_fixtures/v0_38/incoming/block_search_evidence.json
- tools/proto-compiler/src/constants.rs
- tools/proto-compiler/src/main.rs
Specifically for these changes ([Issue](https://github.com/cometbft/cometbft/issues/3528), [PR](https://github.com/cometbft/cometbft/pull/3543))
> rpc: Add new dialect for v0.38 in order to fix changes in misbehaviour evidence serialization

- .changelog/unreleased/bug-fixes/1481-bump-deps-to-fix-broken-compile.md
- light-client-js/Cargo.toml
Fixes failing compilation of `wasm-bindgest-test` by bumping `serde-wasm-bindgen@v0.6.5` and `js-sys@=v0.3.70` (see compilation error at the bottom of these patch notes).
<details><summary>Compilation errors seen in CI:</summary>
```
error[E0152]: found duplicate lang item `panic_impl`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-test-0.3.49/src/rt/mod.rs:321:9
|
321 | /         fn panic_handler(panic_info: &core::panic::PanicInfo<'_>) -> ! {
322 | |             panic_handling(panic_info.to_string());
323 | |             core::arch::wasm32::unreachable();
324 | |         }
| |_________^
|
= note: the lang item is first defined in crate `std` (which `js_sys` depends on)
= note: first definition in `std` loaded from …
```
> fix: bump serde-wasm-bindgen, js-sys to fix broken compile

- .changelog/0.40.1/bug-fixes/1476-export-v0_37-abci-events.md
- .changelog/0.40.1/bug-fixes/1481-bump-deps-to-fix-broken-compile.md
- .changelog/0.40.1/summary.md
- CHANGELOG.md
- abci/Cargo.toml
- config/Cargo.toml
- light-client-cli/Cargo.toml
- light-client-detector/Cargo.toml
- light-client-js/Cargo.toml
- light-client-verifier/Cargo.toml
- light-client/Cargo.toml
- p2p/Cargo.toml
- pbt-gen/Cargo.toml
- proto/Cargo.toml
- rpc/Cargo.toml
- std-ext/Cargo.toml
- tendermint/Cargo.toml
- test/Cargo.toml
- testgen/Cargo.toml
- tools/abci-test/Cargo.toml
- tools/kvstore-test/Cargo.toml
- tools/rpc-probe/Cargo.toml
This prepares a patch release. Open to make this a major one since this contains a bump in `light-client-js`. I am not sure it's necessary though. I don't understand the pin on `js-sys`. I can't see how its absence breaks `no_std`.
> Prepare a patch release `v0.40.1`

- CHANGELOG.md
- rpc/src/client/transport/auth.rs
- rpc/src/client/transport/http.rs
> fix: strip auth info from url to avoid double authorization header

- .changelog/unreleased/bug-fixes/1475-fix-deserialization-from-serde_json_Value.md
- proto/src/serializers.rs
- proto/src/serializers/bytes.rs
- proto/src/serializers/cow_str.rs
- proto/src/serializers/from_str.rs
- proto/src/serializers/from_str_allow_null.rs
- proto/src/serializers/optional_from_str.rs
- proto/src/serializers/time_duration.rs
- proto/src/serializers/timestamp.rs
- proto/src/serializers/txs.rs
- tendermint/src/chain/id.rs
- tendermint/src/hash.rs
- tendermint/src/validator.rs
> fix(tendermint): Fix deserialization from `serde_json::Value`
