docs/architecture/README.md
docs/architecture/adr-001-repo.md
docs/architecture/adr-template.md

Adds to #28, as per comments [here](https://github.com/interchainio/tendermint-rs/pull/28#discussion_r321981398) from @marbar3778.

Minor recommendations for ADR PR

---

tendermint/src/time.rs

Wanted to rebase a branch on master an noticed that the current build seems broken:
https://app.circleci.com/jobs/github/interchainio/tendermint-rs/156
(Introduced via #64)
Not a big thing: It's just a lint/clippy warning. But it'd be nice to have a properly building master branch.

Fix builds on master (clippy errors)

---

tendermint/src/block/header.rs
tendermint/src/block/signed_header.rs
tendermint/src/lib.rs
tendermint/src/lite/types.rs
tendermint/src/lite/verifier.rs
tendermint/src/lite_impl.rs
tendermint/src/lite_impl/header.rs
tendermint/src/lite_impl/signed_header.rs
tendermint/src/lite_impl/validator_set.rs
tendermint/src/validator.rs

Refactor lite impls into their own module within tendermint 

---

.circleci/config.yml
.codecov.yml

- add grcov to circleci and upload coverage metrics to codecov.io
- add cargo audit while at it
Preferably we merge this before other PRs.

Generate code coverage metrics and upload to codecov.io

---

tendermint-lite/src/main.rs
tendermint-lite/src/store.rs
tendermint/Cargo.toml
tendermint/src/block/commit.rs
tendermint/src/block/header.rs
tendermint/src/block/signed_header.rs
tendermint/src/lite/types.rs
tendermint/src/lite/verifier.rs
tendermint/src/lite_impl/signed_header.rs
tendermint/src/signature.rs
tendermint/src/validator.rs
tendermint/src/vote.rs
tendermint/tests/lite.rs

Addresses all comments from #132 (almost all, https://github.com/interchainio/tendermint-rs/pull/132#discussion_r373813746 still needs to be addressed; will be addressed shortly too)

132 followup

---

tendermint/src/lite/types.rs
tendermint/tests/lite.rs
tendermint/tests/support/lite/many_header_bisection/happy_path.json
tendermint/tests/support/lite/single_step_sequential/commit_tests.json

Added some initial code for JSON bisection tests (WIP)

JSON bisection tests

---

tendermint/tests/lite.rs

I should have rebased #155 onto latest master instead. This fixes the build.

Fix master again

---

tendermint/src/lite/types.rs

- Add Serialize/Deserialize instances to TrustedState and SignedHeader
- Change MemStore to use serialization

Make TrustedState serializable, Fix #161

---

tendermint/Cargo.toml
tendermint/tests/integration.rs

Update integration tests to async tests with #[tokio::test]

---

tendermint-lite/src/main.rs
tendermint/src/lite/types.rs
tendermint/src/lite/verifier.rs
tendermint/tests/lite.rs
todo.txt

Make TrustedState::new take ownership of its arguments

---

tendermint/src/lite/types.rs

Require that light client datatypes be serializable

---

CHANGES.md
tendermint/src/rpc/id.rs

* [] Updated all relevant documentation in docs
This is a cherry-pick separation of the JSON ID issue (#88) from the v0.33 branch/PR as requested by @Liamsi .

JSON ID specification compatible

---

docs/spec/fastsync/fastsync.tla

Add fastsync high level TLA+ spec

---

docs/spec/fastsync/fastsync.tla

Add NoBlockResponse

---

tendermint/Cargo.toml
tendermint/src/lib.rs

Release 0.12.0 from master

---

.github/workflows/rust.yml

run rust ci on master
closes #231

ci: run tests & linting on master

---

README.md
tendermint/src/lib.rs

README: Fix CI badges, update minimum Rust version, update logo in docs

---

tendermint/src/rpc/endpoint/abci_info.rs
tendermint/tests/integration.rs

bump abci version in integration tests

---

.github/workflows/rust.yml

CI Rust nightly coverage fix

---

CHANGES.md
tendermint/src/serializers.rs
tendermint/src/serializers/bytes.rs
tendermint/src/serializers/custom.rs
tendermint/src/serializers/from_str.rs
tendermint/src/serializers/tests.rs
tendermint/src/serializers/time_duration.rs

Locked down serialization library to local crate only

---

tendermint/src/block/commit_sig.rs
tendermint/src/serializers/raw_commit_sig.rs
tendermint/tests/lite.rs

Make serialization of CommitSig, TrustedState symmetric

---

tendermint/src/abci.rs
tendermint/src/merkle.rs
tendermint/src/merkle/proof.rs
tendermint/src/rpc/endpoint/abci_query.rs

less confusing if coming from go / working with IBC
closes #207

Move proof.rs to merkle module

---

tendermint/src/rpc/endpoint/broadcast/tx_commit.rs
tendermint/tests/rpc.rs
tendermint/tests/support/rpc/broadcast_tx_commit_null_data.json

Fix null data in TxResult deserialization

---

light-client/examples/light_client.rs
light-client/src/components/io.rs
light-client/src/components/scheduler.rs
light-client/src/errors.rs
light-client/src/light_client.rs
light-client/src/peer_list.rs
light-client/src/store.rs
light-client/src/store/memory.rs
light-client/src/store/sled.rs
light-client/src/supervisor.rs
light-client/tests/light_client.rs

Supervisor follow-up

---

tendermint/Cargo.toml

See https://crates.io/categories/cryptography::cryptocurrencies

tendermint/Cargo.toml: add `cryptography::cryptocurrencies` category

---

rpc/Cargo.toml
rpc/README.md

Part of #339 and should be included before 0.14.0 release: #344 
rendered: https://github.com/informalsystems/tendermint-rs/tree/ismail/rpc_readme/rpc

Document rpc crate

---

light-client/examples/light_client.rs
light-client/src/callback.rs
light-client/src/supervisor.rs
light-client/tests/light_client.rs

Fix a bunch of clippy warnings

---

light-client/Cargo.toml

https://github.com/informalsystems/tendermint-rs/pull/347#discussion_r442901994

consistent versioning across crates 

---

tendermint/Cargo.toml

do not explicitly version dev-dependency

---

tendermint/Cargo.toml

Would be nice to get a point release of `tendermint-rs` which includes this, as I imagine you'll start making breaking changes for Stargate soon

Update `prost-amino`/`prost-amino-derive` to v0.6

---

light-client/src/errors.rs
light-client/src/light_client.rs
light-client/tests/light_client.rs

Fix exit condition in `verify_to_target`

---

light-client/src/operations/voting_power.rs
tendermint/tests/support/lite/voting_power/1_empty_signatures.json
tendermint/tests/support/lite/voting_power/2_1_all_signatures_absent.json
tendermint/tests/support/lite/voting_power/2_2_all_signatures_nil.json
tendermint/tests/support/lite/voting_power/3_1_one_invalid_signature.json
tendermint/tests/support/lite/voting_power/3_2_all_signatures_invalid.json
tendermint/tests/support/lite/voting_power/4_1_missing_a_signature_in_commit.json
tendermint/tests/support/lite/voting_power/4_2_extra_signature_in_commit.json
tendermint/tests/support/lite/voting_power/5_1_all_signatures_from_same_validator.json
tendermint/tests/support/lite/voting_power/5_1_validator_voted_twice.json
tendermint/tests/support/lite/voting_power/7_signatures_from_diff_valset.json

See #320
Thanks @Shivani912 for the JSON testcases :)

Add JSON-based unit tests for VotingPowerCalculator

---

docs/spec/lightclient/Lightclient_A_1.tla

added tracability tags (in the english spec in branch josef/lc-verif)

---

README.md
docs/spec/README.md

Flesh out the readme a bit more.

readme update

---

docs/architecture/adr-007-light-client-supervisor-ergonomics.md

[ADR] Light Client Supervisor Ergonomics

---

light-client/examples/light_client.rs
light-client/src/components/scheduler.rs
light-client/src/light_client.rs
light-client/src/store.rs
light-client/src/store/memory.rs
light-client/src/store/sled.rs
light-client/src/supervisor.rs
light-client/tests/light_client.rs

See https://github.com/informalsystems/tendermint-rs/pull/375/files#r448951616 for context.
This PR also renames `Store::highest` to `Store::latest` for consistency with the spec.

Fetch latest trusted or verified block from the store as latest trusted state

---

light-node/src/error.rs
light-node/src/rpc.rs

cf. https://github.com/informalsystems/tendermint-rs/pull/363/files#r450738893

light-node: track underlying IO errors

---

CHANGES.md

light-client: update changelog

---

.github/workflows/rust.yml

Update tendermint docker image to latest 0.33 release

---

light-client/src/light_client.rs

Fix broken link in light client docs

---

light-client/README.md
light-client/src/evidence.rs
light-client/src/fork_detector.rs
light-client/src/supervisor.rs

Add README to the light-client crate

---

docs/spec/lightclient/README.md
docs/spec/lightclient/verification/verification.md
proto/src/prost/tendermint.abci.rs
proto/src/prost/tendermint.privval.rs
proto/src/prost/tendermint.state.rs
proto/src/prost/tendermint.types.rs

Merge back from master

---

testgen/Cargo.toml
testgen/src/lib.rs
testgen/src/light_block.rs
testgen/src/validator.rs

This added functionality is needed for testing light client. Light block generation is needed by many of those tests and so having it here removes a lot of redundant code from unit tests.

Adds light block generation to testgen

---

tendermint/Cargo.toml
testgen/Cargo.toml

https://twitter.com/isislovecruft/status/1296583478868312064 🎉

Bump `ed25519-dalek` dependency to v1.0 release

---

CHANGELOG.md

Fix up the changelog from  v0.15 - fixes #521

fix v0.15 changelog. fixes #521

---

proto-compiler/Cargo.toml

Closes #518 .
This is an internal fix, no mention of it in the changelog.

Cargo option: Do not publish proto-compiler

---

CHANGELOG.md
light-client/src/light_client.rs
tendermint/src/validator.rs

order validators by voting power

---

tendermint/Cargo.toml
tendermint/src/public_key.rs

Release notes: https://github.com/RustCrypto/elliptic-curves/pull/188

Bump `k256` crate dependency to v0.5

---

CHANGELOG.md
tendermint/src/validator.rs
testgen/src/validator.rs

Fix validator sorting according to v.0.34 requirements

---

tendermint/tests/integration.rs

Closes #562
P.S.: Is it okay to have the check inside the test for `/block` endpoint? Since this is part of block validation, I placed it there.

Add integration test for catching empty merkle root bug

---

rpc/src/client/transport/websocket.rs

rpc: Add WebSocket keepalive mechanism and timeout

---

tendermint/tests/integration.rs

From our discussion in the IBC meeting this morning, I've added an integration test which demonstrates how to create multiple subscriptions and iterate over them concurrently (as a single combined stream).
To run this test:
```bash
docker run -it --rm -v "/tmp/tendermint:/tendermint" tendermint/tendermint init
docker run -it --rm -v "/tmp/tendermint:/tendermint" -p 26657:26657 tendermint/tendermint node --proxy_app=kvstore
cargo test -p tendermint --all-features concurrent_subscriptions -- --nocapture --ignored
```

rpc: Add integration test showing management of concurrent subscriptions

---

light-client/README.md
light-client/tests/support/model_based/README.md

📖 [**Rendered**](https://github.com/informalsystems/tendermint-rs/blob/romac/lc-testing-doc/light-client/README.md#testing)
Close #595

light-client: Add testing-related documentation

---

tendermint/src/block/header.rs

As per https://github.com/informalsystems/tendermint-rs/pull/622#discussion_r501893436

serialization: Simplify block header version app default

---

rpc/src/client/transport/mock.rs
tendermint/src/block/height.rs
tendermint/src/consensus/state.rs
tendermint/src/proposal.rs
tendermint/src/vote/sign_vote.rs
tendermint/tests/integration.rs

Closes #628 
Very cool idea from Romain that I should have thought about.

Height conversion support for u32,u16,u8

---

tendermint/src/block/round.rs
tendermint/src/consensus/state.rs

Fixes #675.
Well, for now. Eventually, we will move serialization as per #654.

State struct JSON serialization

---

proto-compiler/src/functions.rs
proto-compiler/src/main.rs
proto/src/lib.rs
proto/src/tendermint.rs

Small improvement for #654 .
This change will automatically generate the protobuf module structure in tendermint-proto.

Automatic protobuf module structure creation

---

CHANGELOG.md
light-client/Cargo.toml
light-client/src/lib.rs
light-node/Cargo.toml
light-node/src/lib.rs
proto/Cargo.toml
proto/src/lib.rs
rpc-probe/Cargo.toml
rpc/Cargo.toml
tendermint/Cargo.toml
tendermint/src/lib.rs
testgen/Cargo.toml

See the [CHANGELOG](https://github.com/informalsystems/tendermint-rs/blob/release/v0.17.0-rc3/CHANGELOG.md) for details.

Release v0.17.0-rc3

---

light-client/tests/model_based.rs

Re-enable fuzzing

---

testgen/src/lib.rs
testgen/src/validator_set.rs

Adds testgen validator set

---

light-client/src/tests.rs
light-client/tests/light_client.rs
light-client/tests/model_based.rs
light-client/tests/supervisor.rs
light-client/tests/support/bisection/multi_peer/conflicting_headers.json
light-client/tests/support/bisection/multi_peer/conflicting_valid_commits_from_one_of_the_witnesses.json
light-client/tests/support/bisection/multi_peer/conflicting_valid_commits_from_the_only_witness.json
light-client/tests/support/bisection/multi_peer/malicious_validator_set.json
light-client/tests/support/bisection/single_peer/header_out_of_trusting_period.json
light-client/tests/support/bisection/single_peer/not_enough_commits.json

Removes AnonLightBlock from tests

---

tendermint/src/vote/sign_vote.rs
testgen/src/commit.rs

Fix new Clippy warnings as of Rust 1.49

---

CHANGELOG.md
light-client/Cargo.toml
light-client/examples/light_client.rs
light-client/src/store.rs
light-client/src/store/sled.rs
light-node/Cargo.toml
light-node/src/commands/initialize.rs
light-node/src/commands/start.rs

This reverts commit 2381dcf8514a84c46532deae85aa3d7a5f586f64 (#772).
This change should not be part of the upcoming 0.17.1 tendermint-rs release.

Revert #772 until v0.17.1 is out

---

CHANGELOG.md
light-client/Cargo.toml
light-client/src/lib.rs
light-node/Cargo.toml
light-node/src/lib.rs
p2p/Cargo.toml
proto/Cargo.toml
proto/src/lib.rs
rpc/Cargo.toml
tendermint/Cargo.toml
tendermint/src/lib.rs
testgen/Cargo.toml
tools/kvstore-test/Cargo.toml
tools/rpc-probe/Cargo.toml

📖 [CHANGELOG](https://github.com/informalsystems/tendermint-rs/blob/release/v0.17.1/CHANGELOG.md#v0171)
Mainly focuses on fixing #774.

Release v0.17.1

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md

Add bug report and enhancement issue templates

---

light-client/Cargo.toml
light-client/README.md
light-client/tests/model_based.rs
light-client/tests/support/model_based/README.md
testgen/src/command.rs
testgen/src/tester.rs

Improve MBT setup instructions

---

light-client/src/supervisor.rs
light-client/src/tests.rs
testgen/src/light_block.rs

Adds bisection unit tests

---

CHANGELOG.md
light-client/Cargo.toml
light-client/src/lib.rs
light-node/Cargo.toml
light-node/src/lib.rs
p2p/Cargo.toml
proto/Cargo.toml
proto/src/lib.rs
rpc/Cargo.toml
tendermint/Cargo.toml
tendermint/src/lib.rs
testgen/Cargo.toml
tools/kvstore-test/Cargo.toml
tools/rpc-probe/Cargo.toml

:book: [CHANGELOG](https://github.com/informalsystems/tendermint-rs/blob/release/v0.18.0/CHANGELOG.md#v0180)

Release v0.18.0

---

CHANGELOG.md
light-client/Cargo.toml
light-client/src/lib.rs
light-node/Cargo.toml
light-node/src/lib.rs
p2p/Cargo.toml
proto/Cargo.toml
proto/src/lib.rs
release.sh
rpc/Cargo.toml
tendermint/Cargo.toml
tendermint/src/lib.rs
testgen/Cargo.toml
tools/kvstore-test/Cargo.toml
tools/rpc-probe/Cargo.toml

:book: [CHANGELOG](https://github.com/informalsystems/tendermint-rs/blob/release/v0.18.1/CHANGELOG.md)

Release v0.18.1

---

p2p/Cargo.toml
p2p/src/lib.rs
p2p/src/secret_connection.rs

p2p: test SecretConnection

---

tendermint/Cargo.toml

Temporarily patch funty dependency to fix build

---

docs/architecture/adr-001-repo.md

fix typo in adr-001-repo

---

light-client/src/light_client.rs
light-client/src/operations/voting_power.rs
testgen/src/tester.rs

`master`'s [currently broken](https://github.com/informalsystems/tendermint-rs/runs/2557422045) due to failing clippy lints, and this attempts to fix it.

Apply clippy recommendations to fix master

---

light-client/src/light_client.rs
light-client/src/operations/voting_power.rs
p2p/src/error.rs
p2p/src/peer.rs
p2p/src/secret_connection.rs
p2p/src/secret_connection/kdf.rs
p2p/src/secret_connection/nonce.rs
p2p/src/secret_connection/pipe.rs
p2p/src/secret_connection/protocol.rs
p2p/src/secret_connection/public_key.rs
p2p/src/supervisor.rs
testgen/src/tester.rs

Merges the latest code from `master` and applies a number of clippy recommendations to #708.

p2p: apply clippy recommendations to p2p abstractions

---

abci/Cargo.toml
light-client-js/Cargo.toml
light-client/Cargo.toml
pbt-gen/Cargo.toml
rpc/Cargo.toml
testgen/Cargo.toml

Signed-off-by: Alexander Simmerl <a.simmerl@gmail.com>

meta: Add missing crate metadata to satisfy clippy (#888)

---

p2p/Cargo.toml

Follow-up to #901 after [comment](https://github.com/informalsystems/tendermint-rs/pull/901#issuecomment-859030507).

Revert flume pin and specify working version 0.10.7

---

.changelog/unreleased/improvements/925-timestamp-conversion.md
abci/Cargo.toml
p2p/Cargo.toml
proto/Cargo.toml
proto/src/prost/tendermint.crypto.rs
proto/src/prost/tendermint.p2p.rs
proto/src/prost/tendermint.types.rs
proto/src/tendermint.rs
tendermint/Cargo.toml
tendermint/src/time.rs

As per https://github.com/informalsystems/tendermint-rs/issues/925#issuecomment-879283715, we'll reintroduce these changes once the issue's fixed in Prost v0.8.
The audit check will necessarily fail, since we're going back to using Prost v0.7 for now.

Temporarily revert #926

---

tools/rpc-probe/Makefile.toml
tools/rpc-probe/src/kvstore.rs

tools: Add `block_search` method to RPC probe

---

.github/workflows/build.yml
.github/workflows/rust.yml
.github/workflows/test.yml

Applies #1044 to the `v0.23.x` branch.

backport: Execute CI workflows on version-specific branches

---

rpc/src/query.rs
tendermint/src/time.rs

Fixes: #1047, this time for real
* ~Added entry in `.changelog/`~

Expunge more uses of time >0.3.2 API

---

config/Cargo.toml
light-client/Cargo.toml
tendermint/Cargo.toml

backport: Remove unnecessary cdylib artifacts from the build

---

rpc/Cargo.toml
tools/rpc-probe/Cargo.toml

Backport of #1062 for v0.23.x.

backport: Bump getrandom to 0.2 (#1062)

---

.github/workflows/test.yml

ci: Bump grcov version to 0.8.7

---

.changelog/unreleased/dependencies/1113-prost-0.10.md
abci/Cargo.toml
p2p/Cargo.toml
proto/Cargo.toml
proto/src/prost/google.protobuf.rs
proto/src/prost/tendermint.crypto.rs
proto/src/prost/tendermint.p2p.rs
proto/src/prost/tendermint.types.rs
proto/src/tendermint.rs
tendermint/Cargo.toml
tools/proto-compiler/Cargo.toml

[v0.23.x] Update `prost` to v0.10

---

.changelog/unreleased/dependencies/1113-prost-0.10.md
abci/Cargo.toml
p2p/Cargo.toml
proto/Cargo.toml
proto/src/prost/google.protobuf.rs
proto/src/prost/tendermint.crypto.rs
proto/src/prost/tendermint.p2p.rs
proto/src/prost/tendermint.types.rs
proto/src/tendermint.rs
tendermint/Cargo.toml
tools/proto-compiler/Cargo.toml

[master] Update `prost` to v0.10

---

tendermint/src/validator.rs

Minor fix in preparation for #1122.

chore: Fix clippy warning

---

rpc/src/client/transport/websocket.rs
testgen/src/apalache.rs

Fixes some minor clippy lints.

clippy: Fix lints for Rust 1.62 (master)

---

.changelog/unreleased/dependencies/1165-bump-async-tungstenite.md
rpc/Cargo.toml
tools/rpc-probe/Cargo.toml

Bump async-tungstenite to 0.17

---

rpc/src/client/transport/http.rs
rpc/src/client/transport/websocket.rs

Add `debug!` trace for the outgoing RPC request

---

README.md

Minor addition to `main` README.

Add Tendermint Core compatibility note in readme

---

light-client-verifier/src/options.rs
light-client-verifier/src/types.rs
light-client/tests/model_based.rs
p2p/src/secret_connection/amino_types.rs
rpc/src/endpoint/consensus_state.rs
rpc/src/endpoint/evidence.rs
rpc/src/event.rs
rpc/src/query.rs
tendermint/src/abci/responses.rs
tendermint/src/abci/tag.rs
tendermint/src/abci/transaction.rs
tendermint/src/block.rs
tendermint/src/evidence.rs
tendermint/src/proposal.rs
tendermint/src/proposal/canonical_proposal.rs
tendermint/src/proposal/sign_proposal.rs
tendermint/src/public_key/pub_key_request.rs
tendermint/src/validator.rs
tendermint/src/vote.rs
tendermint/src/vote/canonical_vote.rs
tendermint/src/vote/sign_vote.rs
testgen/src/light_block.rs

A trivial, mechanical PR to appease clippy to prevent CI errors.

chore: Derive Eq to appease latest version of clippy

---

docs/architecture/adr-012-multi-version.md

[Rendered](https://github.com/informalsystems/tendermint-rs/blob/mikhail/adr-012-multi-version/docs/architecture/adr-012-multi-version.md)

ADR 012: Multi-Version Support

---

rpc/Cargo.toml
rpc/src/client/transport/http.rs
rpc/src/dialect.rs
rpc/src/dialect/v0_34.rs
rpc/src/dialect/v0_37.rs
rpc/src/endpoint/evidence.rs
tendermint/src/consensus/params.rs
tendermint/src/evidence.rs

Dialect-based evidence serialization

---

.changelog/unreleased/bug-fixes/1326-compat-for-latest_block_results.md
.changelog/v0.32.1/bug-fixes/1326-compat-for-latest_block_results.md
.changelog/v0.32.1/summary.md
CHANGELOG.md
abci/Cargo.toml
abci/tests/echo_app.rs
config/Cargo.toml
light-client-cli/Cargo.toml
light-client-detector/Cargo.toml
light-client-js/Cargo.toml
light-client-verifier/Cargo.toml
light-client-verifier/src/predicates.rs
light-client/Cargo.toml
p2p/Cargo.toml
pbt-gen/Cargo.toml
proto/Cargo.toml
rpc/Cargo.toml
rpc/src/client/transport/http.rs
rpc/src/client/transport/websocket.rs
std-ext/Cargo.toml
tendermint/Cargo.toml
tendermint/src/hash.rs
tendermint/src/time.rs
test/Cargo.toml
testgen/Cargo.toml
testgen/src/tester.rs
tools/abci-test/Cargo.toml
tools/kvstore-test/Cargo.toml
tools/rpc-probe/Cargo.toml

Cherry-picking a compatibility mode bugfix on top of 0.32.0.
The upcoming 0.33.0 release contains some breaking changes, so we should provide a less intrusive fix for the earlier release.

Release 0.32.1

---

docs/architecture/adr-003-light-client-core-verification.md
docs/spec/tendermint-fork-cases/README.md
light-client-verifier/src/errors.rs

fix: some typos

---

light-client-verifier/src/verifier.rs
tendermint/src/abci/event.rs
tendermint/src/merkle.rs

Fix warnings on nightly

---

abci/src/application/kvstore.rs
docs/spec/lightclient/verification/Lightclient_A_1.tla
light-client-verifier/src/operations/commit_validator.rs
light-client/tests/support/model_based/Lightclient_003_draft.tla
tendermint/src/block/signed_header.rs
tendermint/src/time.rs

chore: remove repetitive words

---

docs/architecture/adr-002-light-client-adr-index.md
docs/architecture/adr-010-time-api-sanity.md
docs/architecture/adr-012-multi-version.md

hey, found really few typos while taking a look at the docs. nothing critical. otherwise it's pretty nicely written, good job!

chore(docs): typo fix

---

light-client-verifier/src/operations/voting_power.rs
light-client/src/components/scheduler.rs
p2p/src/secret_connection.rs
pbt-gen/src/lib.rs
rpc/src/client/transport/router.rs
test/src/test/unit/p2p/secret_connection.rs

Fix new clippy warnings on Rust 1.80

---

proto/src/prost/v0_34/tendermint.abci.rs
proto/src/prost/v0_37/tendermint.abci.rs
proto/src/prost/v0_38/tendermint.abci.rs
rpc/src/client/transport/websocket.rs
rpc/src/dialect/check_tx.rs
tendermint/src/abci/response/finalize_block.rs

chore: fix some comments
